# GD-DOOM runtime config
# CLI flags override values set here.

wad = "DOOM1.WAD"
map = ""
render = true
debug = false
details = false

width = 2560
height = 1440
zoom = 0.0
player = 1
skill = 3

line_color_mode = "parity"
sourceport_mode = false
all_cheats = false
start_in_map = false
import_pcspeaker = true
