// Code generated by TestGenerateAuthorityBinaryCodec; DO NOT EDIT.
package doomruntime

import (
	"fmt"
	"gddoom/internal/mapdata"
	"gddoom/internal/render/mapview"
	"maps"
	"slices"
	"strconv"
)

var authorityBinarySchemaFingerprint = [16]byte{0xea, 0x5f, 0x1c, 0xa0, 0x9f, 0x3b, 0x15, 0x47, 0x09, 0x02, 0xa0, 0xbe, 0x08, 0x75, 0xfb, 0x6a}

func (w *authorityBinaryWriter) writedoomruntime_AuthorityRules(v *AuthorityRules) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.FragLimit))
	w.unsigned(uint64(v.TimeLimitTics))
	w.unsigned(uint64(v.RespawnDelayTics))
	w.boolean(bool(v.FriendlyFire))
}
func (r *authorityBinaryReader) readdoomruntime_AuthorityRules(v *AuthorityRules) {
	if r.err != nil {
		return
	}
	v.FragLimit = int(r.signed(strconv.IntSize))
	v.TimeLimitTics = uint32(r.unsigned(32))
	v.RespawnDelayTics = uint32(r.unsigned(32))
	v.FriendlyFire = bool(r.boolean())
}
func (w *authorityBinaryWriter) writedoomruntime_authorityBarrelSource(v *authorityBarrelSource) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.PlayerSlot))
	w.unsigned(uint64(v.PlayerGeneration))
	w.signed(int64(v.Thing))
}
func (r *authorityBinaryReader) readdoomruntime_authorityBarrelSource(v *authorityBarrelSource) {
	if r.err != nil {
		return
	}
	v.PlayerSlot = int(r.signed(strconv.IntSize))
	v.PlayerGeneration = uint32(r.unsigned(32))
	v.Thing = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_authorityReplica(v *authorityReplica) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Version))
	w.string(string(v.Map))
	w.raw(v.MapHash[:])
	w.string(string(v.WADHash))
	w.byte(byte(v.Viewer))
	w.unsigned(uint64(v.Tic))
	w.writedoomruntime_gameSaveState(&v.Game)
	if !w.collection(len(v.Players), v.Players == nil, authorityBinarySizeOf[authorityReplicaPlayer]()) {
		return
	}
	for tmp1 := range v.Players {
		if w.err != nil {
			return
		}
		w.writedoomruntime_authorityReplicaPlayer(&v.Players[tmp1])
	}
	if !w.collection(len(v.ThingBlockOrder), v.ThingBlockOrder == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp2 := range v.ThingBlockOrder {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingBlockOrder[tmp2]))
	}
	if !w.collection(len(v.ThingTelefragTick), v.ThingTelefragTick == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp3 := range v.ThingTelefragTick {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingTelefragTick[tmp3]))
	}
	if !w.collection(len(v.ThingTargetPlayerSlot), v.ThingTargetPlayerSlot == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp4 := range v.ThingTargetPlayerSlot {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingTargetPlayerSlot[tmp4]))
	}
	if !w.collection(len(v.SectorSoundPlayerSlot), v.SectorSoundPlayerSlot == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp5 := range v.SectorSoundPlayerSlot {
		if w.err != nil {
			return
		}
		w.signed(int64(v.SectorSoundPlayerSlot[tmp5]))
	}
	if !w.collection(len(v.ProjectilePlayers), v.ProjectilePlayers == nil, authorityBinarySizeOf[replicaProjectilePlayers]()) {
		return
	}
	for tmp6 := range v.ProjectilePlayers {
		if w.err != nil {
			return
		}
		w.writedoomruntime_replicaProjectilePlayers(&v.ProjectilePlayers[tmp6])
	}
	if !w.collection(len(v.ImpactPlayers), v.ImpactPlayers == nil, authorityBinarySizeOf[replicaImpactPlayers]()) {
		return
	}
	for tmp7 := range v.ImpactPlayers {
		if w.err != nil {
			return
		}
		w.writedoomruntime_replicaImpactPlayers(&v.ImpactPlayers[tmp7])
	}
	if !w.collection(len(v.BarrelSources), v.BarrelSources == nil, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[authorityBarrelSource]()+16)) {
		return
	}
	tmp8 := make([]int, 0, len(v.BarrelSources))
	for tmp9 := range v.BarrelSources {
		tmp8 = append(tmp8, tmp9)
	}
	slices.Sort(tmp8)
	for _, tmp9 := range tmp8 {
		if w.err != nil {
			return
		}
		tmp10 := v.BarrelSources[tmp9]
		w.signed(int64(tmp9))
		w.writedoomruntime_authorityBarrelSource(&tmp10)
	}
	w.unsigned(uint64(v.SoundCursor))
	if !w.collection(len(v.Sounds), v.Sounds == nil, authorityBinarySizeOf[authoritySoundEvent]()) {
		return
	}
	for tmp11 := range v.Sounds {
		if w.err != nil {
			return
		}
		w.writedoomruntime_authoritySoundEvent(&v.Sounds[tmp11])
	}
	w.boolean(v.Rules != nil)
	if v.Rules != nil {
		if !w.allocate(1, authorityBinarySizeOf[authorityRulesState]()) {
			return
		}
		w.writedoomruntime_authorityRulesState(&(*v.Rules))
	}
}
func (r *authorityBinaryReader) readdoomruntime_authorityReplica(v *authorityReplica) {
	if r.err != nil {
		return
	}
	v.Version = int(r.signed(strconv.IntSize))
	v.Map = mapdata.MapName(r.string())
	copy(v.MapHash[:], r.raw(32))
	v.WADHash = string(r.string())
	v.Viewer = uint8(r.byte())
	v.Tic = uint32(r.unsigned(32))
	r.readdoomruntime_gameSaveState(&v.Game)
	tmp12, tmp13 := r.collection(104, authorityBinarySizeOf[authorityReplicaPlayer]())
	if r.err != nil {
		return
	}
	if tmp13 {
		v.Players = make([]authorityReplicaPlayer, tmp12)
		for tmp14 := range v.Players {
			if r.err != nil {
				return
			}
			r.readdoomruntime_authorityReplicaPlayer(&v.Players[tmp14])
		}
	}
	tmp15, tmp16 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp16 {
		v.ThingBlockOrder = make([]int64, tmp15)
		for tmp17 := range v.ThingBlockOrder {
			if r.err != nil {
				return
			}
			v.ThingBlockOrder[tmp17] = int64(r.signed(64))
		}
	}
	tmp18, tmp19 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp19 {
		v.ThingTelefragTick = make([]int, tmp18)
		for tmp20 := range v.ThingTelefragTick {
			if r.err != nil {
				return
			}
			v.ThingTelefragTick[tmp20] = int(r.signed(strconv.IntSize))
		}
	}
	tmp21, tmp22 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp22 {
		v.ThingTargetPlayerSlot = make([]int, tmp21)
		for tmp23 := range v.ThingTargetPlayerSlot {
			if r.err != nil {
				return
			}
			v.ThingTargetPlayerSlot[tmp23] = int(r.signed(strconv.IntSize))
		}
	}
	tmp24, tmp25 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp25 {
		v.SectorSoundPlayerSlot = make([]int, tmp24)
		for tmp26 := range v.SectorSoundPlayerSlot {
			if r.err != nil {
				return
			}
			v.SectorSoundPlayerSlot[tmp26] = int(r.signed(strconv.IntSize))
		}
	}
	tmp27, tmp28 := r.collection(4, authorityBinarySizeOf[replicaProjectilePlayers]())
	if r.err != nil {
		return
	}
	if tmp28 {
		v.ProjectilePlayers = make([]replicaProjectilePlayers, tmp27)
		for tmp29 := range v.ProjectilePlayers {
			if r.err != nil {
				return
			}
			r.readdoomruntime_replicaProjectilePlayers(&v.ProjectilePlayers[tmp29])
		}
	}
	tmp30, tmp31 := r.collection(4, authorityBinarySizeOf[replicaImpactPlayers]())
	if r.err != nil {
		return
	}
	if tmp31 {
		v.ImpactPlayers = make([]replicaImpactPlayers, tmp30)
		for tmp32 := range v.ImpactPlayers {
			if r.err != nil {
				return
			}
			r.readdoomruntime_replicaImpactPlayers(&v.ImpactPlayers[tmp32])
		}
	}
	tmp33, tmp34 := r.collection(4, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[authorityBarrelSource]()+16))
	if r.err != nil {
		return
	}
	if tmp34 {
		v.BarrelSources = make(map[int]authorityBarrelSource, tmp33)
		var tmp37 int
		for tmp38 := 0; tmp38 < tmp33; tmp38++ {
			if r.err != nil {
				return
			}
			var tmp35 int
			var tmp36 authorityBarrelSource
			tmp35 = int(r.signed(strconv.IntSize))
			if tmp38 > 0 && tmp35 <= tmp37 {
				r.fail("unordered or duplicate map key")
				return
			}
			tmp37 = tmp35
			r.readdoomruntime_authorityBarrelSource(&tmp36)
			v.BarrelSources[tmp35] = tmp36
		}
	}
	v.SoundCursor = uint64(r.unsigned(64))
	tmp39, tmp40 := r.collection(7, authorityBinarySizeOf[authoritySoundEvent]())
	if r.err != nil {
		return
	}
	if tmp40 {
		v.Sounds = make([]authoritySoundEvent, tmp39)
		for tmp41 := range v.Sounds {
			if r.err != nil {
				return
			}
			r.readdoomruntime_authoritySoundEvent(&v.Sounds[tmp41])
		}
	}
	if r.boolean() {
		if !r.allocate(1, authorityBinarySizeOf[authorityRulesState]()) {
			return
		}
		v.Rules = new(authorityRulesState)
		r.readdoomruntime_authorityRulesState(&(*v.Rules))
	}
}
func (w *authorityBinaryWriter) writedoomruntime_authorityReplicaPlayer(v *authorityReplicaPlayer) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.AuthorityPlayerThinkerOrder))
	w.boolean(bool(v.TeleportedThisTic))
	w.writedoomruntime_playerSaveState(&v.P)
	w.writedoomruntime_replicaMoveCommand(&v.CurrentMoveCmd)
	w.signed(int64(v.LastAttackRange))
	w.signed(int64(v.LocalSlot))
	w.signed(int64(v.LocalPlayerThingIndex))
	w.signed(int64(v.PlayerBlockOrder))
	w.signed(int64(v.TurnHeld))
	w.signed(int64(v.CheatLevel))
	w.boolean(bool(v.Invulnerable))
	w.boolean(bool(v.NoClip))
	w.writedoomruntime_playerInventorySaveState(&v.Inventory)
	w.boolean(bool(v.AlwaysRun))
	w.boolean(bool(v.AutoWeaponSwitch))
	w.boolean(bool(v.WeaponRefire))
	w.boolean(bool(v.WeaponAttackDown))
	w.boolean(bool(v.UseButtonDown))
	w.signed(int64(v.PrevWeaponState))
	w.signed(int64(v.PrevWeaponFlashState))
	w.signed(int64(v.PrevWeaponPSpriteY))
	w.signed(int64(v.WeaponState))
	w.signed(int64(v.WeaponStateTics))
	w.signed(int64(v.WeaponFlashState))
	w.signed(int64(v.WeaponFlashTics))
	w.signed(int64(v.WeaponPSpriteY))
	w.writedoomruntime_playerStats(&v.Stats)
	w.signed(int64(v.PlayerKillCount))
	w.signed(int64(v.PlayerItemCount))
	w.signed(int64(v.PlayerViewZ))
	w.signed(int64(v.SecretsFound))
	w.boolean(bool(v.IsDead))
	w.boolean(bool(v.PlayerReborn))
	w.signed(int64(v.PlayerMobjHealth))
	w.signed(int64(v.DamageFlashTic))
	w.signed(int64(v.BonusFlashTic))
	w.signed(int64(v.StatusFaceIndex))
	w.signed(int64(v.StatusFaceCount))
	w.signed(int64(v.StatusFacePriority))
	w.signed(int64(v.StatusOldHealth))
	w.signed(int64(v.StatusRandom))
	w.signed(int64(v.StatusLastAttack))
	w.boolean(bool(v.StatusAttackDown))
	w.signed(int64(v.StatusAttackerX))
	w.signed(int64(v.StatusAttackerY))
	w.signed(int64(v.StatusAttackerThing))
	w.boolean(bool(v.StatusHasAttacker))
	for tmp42 := range v.StatusOldWeapons {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.StatusOldWeapons[tmp42]))
	}
	w.signed(int64(v.StatusDamageCount))
	w.signed(int64(v.StatusBonusCount))
	w.signed(int64(v.PlayerMobjState))
	w.signed(int64(v.PlayerMobjTics))
	w.signed(int64(v.UseFlash))
	w.string(string(v.UseText))
	w.signed(int64(v.PrevPX))
	w.signed(int64(v.PrevPY))
	w.unsigned(uint64(v.PrevAngle))
	w.unsigned(uint64(v.PrevPrevAngle))
}
func (r *authorityBinaryReader) readdoomruntime_authorityReplicaPlayer(v *authorityReplicaPlayer) {
	if r.err != nil {
		return
	}
	v.AuthorityPlayerThinkerOrder = int64(r.signed(64))
	v.TeleportedThisTic = bool(r.boolean())
	r.readdoomruntime_playerSaveState(&v.P)
	r.readdoomruntime_replicaMoveCommand(&v.CurrentMoveCmd)
	v.LastAttackRange = int64(r.signed(64))
	v.LocalSlot = int(r.signed(strconv.IntSize))
	v.LocalPlayerThingIndex = int(r.signed(strconv.IntSize))
	v.PlayerBlockOrder = int64(r.signed(64))
	v.TurnHeld = int(r.signed(strconv.IntSize))
	v.CheatLevel = int(r.signed(strconv.IntSize))
	v.Invulnerable = bool(r.boolean())
	v.NoClip = bool(r.boolean())
	r.readdoomruntime_playerInventorySaveState(&v.Inventory)
	v.AlwaysRun = bool(r.boolean())
	v.AutoWeaponSwitch = bool(r.boolean())
	v.WeaponRefire = bool(r.boolean())
	v.WeaponAttackDown = bool(r.boolean())
	v.UseButtonDown = bool(r.boolean())
	v.PrevWeaponState = weaponPspriteState(r.signed(strconv.IntSize))
	v.PrevWeaponFlashState = weaponPspriteState(r.signed(strconv.IntSize))
	v.PrevWeaponPSpriteY = int(r.signed(strconv.IntSize))
	v.WeaponState = weaponPspriteState(r.signed(strconv.IntSize))
	v.WeaponStateTics = int(r.signed(strconv.IntSize))
	v.WeaponFlashState = weaponPspriteState(r.signed(strconv.IntSize))
	v.WeaponFlashTics = int(r.signed(strconv.IntSize))
	v.WeaponPSpriteY = int(r.signed(strconv.IntSize))
	r.readdoomruntime_playerStats(&v.Stats)
	v.PlayerKillCount = int(r.signed(strconv.IntSize))
	v.PlayerItemCount = int(r.signed(strconv.IntSize))
	v.PlayerViewZ = int64(r.signed(64))
	v.SecretsFound = int(r.signed(strconv.IntSize))
	v.IsDead = bool(r.boolean())
	v.PlayerReborn = bool(r.boolean())
	v.PlayerMobjHealth = int(r.signed(strconv.IntSize))
	v.DamageFlashTic = int(r.signed(strconv.IntSize))
	v.BonusFlashTic = int(r.signed(strconv.IntSize))
	v.StatusFaceIndex = int(r.signed(strconv.IntSize))
	v.StatusFaceCount = int(r.signed(strconv.IntSize))
	v.StatusFacePriority = int(r.signed(strconv.IntSize))
	v.StatusOldHealth = int(r.signed(strconv.IntSize))
	v.StatusRandom = int(r.signed(strconv.IntSize))
	v.StatusLastAttack = int(r.signed(strconv.IntSize))
	v.StatusAttackDown = bool(r.boolean())
	v.StatusAttackerX = int64(r.signed(64))
	v.StatusAttackerY = int64(r.signed(64))
	v.StatusAttackerThing = int(r.signed(strconv.IntSize))
	v.StatusHasAttacker = bool(r.boolean())
	for tmp43 := range v.StatusOldWeapons {
		if r.err != nil {
			return
		}
		v.StatusOldWeapons[tmp43] = bool(r.boolean())
	}
	v.StatusDamageCount = int(r.signed(strconv.IntSize))
	v.StatusBonusCount = int(r.signed(strconv.IntSize))
	v.PlayerMobjState = int(r.signed(strconv.IntSize))
	v.PlayerMobjTics = int(r.signed(strconv.IntSize))
	v.UseFlash = int(r.signed(strconv.IntSize))
	v.UseText = string(r.string())
	v.PrevPX = int64(r.signed(64))
	v.PrevPY = int64(r.signed(64))
	v.PrevAngle = uint32(r.unsigned(32))
	v.PrevPrevAngle = uint32(r.unsigned(32))
}
func (w *authorityBinaryWriter) writedoomruntime_authorityRulesState(v *authorityRulesState) {
	if w.err != nil {
		return
	}
	w.writedoomruntime_AuthorityRules(&v.Config)
	for tmp44 := range v.Scores {
		if w.err != nil {
			return
		}
		w.writedoomruntime_authorityScoreState(&v.Scores[tmp44])
	}
	w.signed(int64(v.SpawnCursor))
	w.unsigned(uint64(v.StartedTic))
	w.boolean(bool(v.Ended))
	w.string(string(v.EndReason))
	w.byte(byte(v.WinnerID))
	w.writemapdata_KeyRing(&v.TeamKeys)
}
func (r *authorityBinaryReader) readdoomruntime_authorityRulesState(v *authorityRulesState) {
	if r.err != nil {
		return
	}
	r.readdoomruntime_AuthorityRules(&v.Config)
	for tmp45 := range v.Scores {
		if r.err != nil {
			return
		}
		r.readdoomruntime_authorityScoreState(&v.Scores[tmp45])
	}
	v.SpawnCursor = int(r.signed(strconv.IntSize))
	v.StartedTic = uint32(r.unsigned(32))
	v.Ended = bool(r.boolean())
	v.EndReason = string(r.string())
	v.WinnerID = uint8(r.byte())
	r.readmapdata_KeyRing(&v.TeamKeys)
}
func (w *authorityBinaryWriter) writedoomruntime_authorityScoreState(v *authorityScoreState) {
	if w.err != nil {
		return
	}
	w.unsigned(uint64(v.Generation))
	w.unsigned(uint64(v.MovementEpoch))
	w.signed(int64(v.Frags))
	w.signed(int64(v.Deaths))
	w.boolean(bool(v.DeathRecorded))
	w.unsigned(uint64(v.DeathTic))
	w.boolean(bool(v.RespawnPending))
}
func (r *authorityBinaryReader) readdoomruntime_authorityScoreState(v *authorityScoreState) {
	if r.err != nil {
		return
	}
	v.Generation = uint32(r.unsigned(32))
	v.MovementEpoch = uint32(r.unsigned(32))
	v.Frags = int(r.signed(strconv.IntSize))
	v.Deaths = int(r.signed(strconv.IntSize))
	v.DeathRecorded = bool(r.boolean())
	v.DeathTic = uint32(r.unsigned(32))
	v.RespawnPending = bool(r.boolean())
}
func (w *authorityBinaryWriter) writedoomruntime_authoritySoundEvent(v *authoritySoundEvent) {
	if w.err != nil {
		return
	}
	w.unsigned(uint64(v.ID))
	w.unsigned(uint64(v.Tick))
	w.signed(int64(v.Kind))
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.byte(byte(v.LocalPlayer))
	w.byte(byte(v.Audience))
}
func (r *authorityBinaryReader) readdoomruntime_authoritySoundEvent(v *authoritySoundEvent) {
	if r.err != nil {
		return
	}
	v.ID = uint64(r.unsigned(64))
	v.Tick = uint32(r.unsigned(32))
	v.Kind = soundEvent(r.signed(strconv.IntSize))
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.LocalPlayer = uint8(r.byte())
	v.Audience = uint8(r.byte())
}
func (w *authorityBinaryWriter) writedoomruntime_bossSpawnCubeSaveState(v *bossSpawnCubeSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.signed(int64(v.FloorZ))
	w.signed(int64(v.CeilZ))
	w.unsigned(uint64(v.Angle))
	w.signed(int64(v.LastLook))
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Z))
	w.signed(int64(v.VX))
	w.signed(int64(v.VY))
	w.signed(int64(v.VZ))
	w.signed(int64(v.TargetIdx))
	w.signed(int64(v.StateTics))
	w.signed(int64(v.StateStep))
	w.signed(int64(v.Reaction))
}
func (r *authorityBinaryReader) readdoomruntime_bossSpawnCubeSaveState(v *bossSpawnCubeSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.FloorZ = int64(r.signed(64))
	v.CeilZ = int64(r.signed(64))
	v.Angle = uint32(r.unsigned(32))
	v.LastLook = int(r.signed(strconv.IntSize))
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.Z = int64(r.signed(64))
	v.VX = int64(r.signed(64))
	v.VY = int64(r.signed(64))
	v.VZ = int64(r.signed(64))
	v.TargetIdx = int(r.signed(strconv.IntSize))
	v.StateTics = int(r.signed(strconv.IntSize))
	v.StateStep = int(r.signed(strconv.IntSize))
	v.Reaction = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_bossSpawnFireSaveState(v *bossSpawnFireSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.signed(int64(v.FloorZ))
	w.signed(int64(v.CeilZ))
	w.signed(int64(v.LastLook))
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Z))
	w.signed(int64(v.Tics))
}
func (r *authorityBinaryReader) readdoomruntime_bossSpawnFireSaveState(v *bossSpawnFireSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.FloorZ = int64(r.signed(64))
	v.CeilZ = int64(r.signed(64))
	v.LastLook = int(r.signed(strconv.IntSize))
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.Z = int64(r.signed(64))
	v.Tics = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_ceilingThinkerSaveState(v *ceilingThinkerSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.signed(int64(v.Sector))
	w.string(string(v.Action))
	w.signed(int64(v.Direction))
	w.signed(int64(v.OldDirection))
	w.signed(int64(v.Speed))
	w.signed(int64(v.TopHeight))
	w.signed(int64(v.BottomHeight))
	w.boolean(bool(v.Crush))
}
func (r *authorityBinaryReader) readdoomruntime_ceilingThinkerSaveState(v *ceilingThinkerSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.Sector = int(r.signed(strconv.IntSize))
	v.Action = mapdata.CeilingAction(r.string())
	v.Direction = int(r.signed(strconv.IntSize))
	v.OldDirection = int(r.signed(strconv.IntSize))
	v.Speed = int64(r.signed(64))
	v.TopHeight = int64(r.signed(64))
	v.BottomHeight = int64(r.signed(64))
	v.Crush = bool(r.boolean())
}
func (w *authorityBinaryWriter) writedoomruntime_delayedSwitchTextureSaveState(v *delayedSwitchTextureSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Line))
	w.signed(int64(v.Sidedef))
	w.string(string(v.Top))
	w.string(string(v.Bottom))
	w.string(string(v.Mid))
	w.signed(int64(v.Tics))
}
func (r *authorityBinaryReader) readdoomruntime_delayedSwitchTextureSaveState(v *delayedSwitchTextureSaveState) {
	if r.err != nil {
		return
	}
	v.Line = int(r.signed(strconv.IntSize))
	v.Sidedef = int(r.signed(strconv.IntSize))
	v.Top = string(r.string())
	v.Bottom = string(r.string())
	v.Mid = string(r.string())
	v.Tics = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_doorThinkerSaveState(v *doorThinkerSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.signed(int64(v.Sector))
	w.signed(int64(v.Type))
	w.signed(int64(v.Direction))
	w.signed(int64(v.TopHeight))
	w.signed(int64(v.TopWait))
	w.signed(int64(v.TopCountdown))
	w.signed(int64(v.Speed))
}
func (r *authorityBinaryReader) readdoomruntime_doorThinkerSaveState(v *doorThinkerSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.Sector = int(r.signed(strconv.IntSize))
	v.Type = int(r.signed(strconv.IntSize))
	v.Direction = int(r.signed(strconv.IntSize))
	v.TopHeight = int64(r.signed(64))
	v.TopWait = int(r.signed(strconv.IntSize))
	v.TopCountdown = int(r.signed(strconv.IntSize))
	v.Speed = int64(r.signed(64))
}
func (w *authorityBinaryWriter) writedoomruntime_floorThinkerSaveState(v *floorThinkerSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.signed(int64(v.Sector))
	w.signed(int64(v.Direction))
	w.signed(int64(v.Speed))
	w.signed(int64(v.DestHeight))
	w.byte(byte(v.Finish))
	w.string(string(v.FinishFlat))
	w.signed(int64(v.FinishSpecial))
}
func (r *authorityBinaryReader) readdoomruntime_floorThinkerSaveState(v *floorThinkerSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.Sector = int(r.signed(strconv.IntSize))
	v.Direction = int(r.signed(strconv.IntSize))
	v.Speed = int64(r.signed(64))
	v.DestHeight = int64(r.signed(64))
	v.Finish = uint8(r.byte())
	v.FinishFlat = string(r.string())
	v.FinishSpecial = int16(r.signed(16))
}
func (w *authorityBinaryWriter) writedoomruntime_gameSaveState(v *gameSaveState) {
	if w.err != nil {
		return
	}
	w.writedoomruntime_sessionSaveState(&v.Session)
	w.writedoomruntime_playerSaveState(&v.Player)
	w.writemapview_ViewState(&v.View)
	w.signed(int64(v.Mode))
	w.boolean(bool(v.RotateView))
	w.signed(int64(v.ParityReveal))
	w.signed(int64(v.ParityIDDT))
	w.boolean(bool(v.ShowGrid))
	w.boolean(bool(v.ShowLegend))
	w.boolean(bool(v.PaletteLUTEnabled))
	w.signed(int64(v.GammaLevel))
	w.boolean(bool(v.CRTEnabled))
	w.signed(int64(v.UseFlash))
	w.string(string(v.UseText))
	w.boolean(bool(v.HUDMessagesEnabled))
	w.signed(int64(v.PrevPX))
	w.signed(int64(v.PrevPY))
	w.unsigned(uint64(v.PrevAngle))
	w.signed(int64(v.PlayerViewZ))
	if !w.collection(len(v.ThingCollected), v.ThingCollected == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp46 := range v.ThingCollected {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingCollected[tmp46]))
	}
	if !w.collection(len(v.ThingDropped), v.ThingDropped == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp47 := range v.ThingDropped {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingDropped[tmp47]))
	}
	if !w.collection(len(v.ThingThinkerOrder), v.ThingThinkerOrder == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp48 := range v.ThingThinkerOrder {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingThinkerOrder[tmp48]))
	}
	if !w.collection(len(v.ThingSpawnPoint), v.ThingSpawnPoint == nil, authorityBinarySizeOf[mapdata.Thing]()) {
		return
	}
	for tmp49 := range v.ThingSpawnPoint {
		if w.err != nil {
			return
		}
		w.writemapdata_Thing(&v.ThingSpawnPoint[tmp49])
	}
	if !w.collection(len(v.ThingX), v.ThingX == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp50 := range v.ThingX {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingX[tmp50]))
	}
	if !w.collection(len(v.ThingY), v.ThingY == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp51 := range v.ThingY {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingY[tmp51]))
	}
	if !w.collection(len(v.ThingMomX), v.ThingMomX == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp52 := range v.ThingMomX {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingMomX[tmp52]))
	}
	if !w.collection(len(v.ThingMomY), v.ThingMomY == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp53 := range v.ThingMomY {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingMomY[tmp53]))
	}
	if !w.collection(len(v.ThingMomZ), v.ThingMomZ == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp54 := range v.ThingMomZ {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingMomZ[tmp54]))
	}
	if !w.collection(len(v.ThingAngleState), v.ThingAngleState == nil, authorityBinarySizeOf[uint32]()) {
		return
	}
	for tmp55 := range v.ThingAngleState {
		if w.err != nil {
			return
		}
		w.unsigned(uint64(v.ThingAngleState[tmp55]))
	}
	if !w.collection(len(v.ThingZState), v.ThingZState == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp56 := range v.ThingZState {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingZState[tmp56]))
	}
	if !w.collection(len(v.ThingFloorState), v.ThingFloorState == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp57 := range v.ThingFloorState {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingFloorState[tmp57]))
	}
	if !w.collection(len(v.ThingCeilState), v.ThingCeilState == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp58 := range v.ThingCeilState {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingCeilState[tmp58]))
	}
	if !w.collection(len(v.ThingSupportValid), v.ThingSupportValid == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp59 := range v.ThingSupportValid {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingSupportValid[tmp59]))
	}
	if !w.collection(len(v.ThingHP), v.ThingHP == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp60 := range v.ThingHP {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingHP[tmp60]))
	}
	if !w.collection(len(v.ThingAggro), v.ThingAggro == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp61 := range v.ThingAggro {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingAggro[tmp61]))
	}
	if !w.collection(len(v.ThingTargetPlayer), v.ThingTargetPlayer == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp62 := range v.ThingTargetPlayer {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingTargetPlayer[tmp62]))
	}
	if !w.collection(len(v.ThingTargetIdx), v.ThingTargetIdx == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp63 := range v.ThingTargetIdx {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingTargetIdx[tmp63]))
	}
	if !w.collection(len(v.ThingTracerFireOrder), v.ThingTracerFireOrder == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp64 := range v.ThingTracerFireOrder {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingTracerFireOrder[tmp64]))
	}
	if !w.collection(len(v.ThingThreshold), v.ThingThreshold == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp65 := range v.ThingThreshold {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingThreshold[tmp65]))
	}
	if !w.collection(len(v.ThingCooldown), v.ThingCooldown == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp66 := range v.ThingCooldown {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingCooldown[tmp66]))
	}
	if !w.collection(len(v.ThingMoveDir), v.ThingMoveDir == nil, authorityBinarySizeOf[uint8]()) {
		return
	}
	w.raw(v.ThingMoveDir[:])
	if !w.collection(len(v.ThingMoveCount), v.ThingMoveCount == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp67 := range v.ThingMoveCount {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingMoveCount[tmp67]))
	}
	if !w.collection(len(v.ThingJustAtk), v.ThingJustAtk == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp68 := range v.ThingJustAtk {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingJustAtk[tmp68]))
	}
	if !w.collection(len(v.ThingJustHit), v.ThingJustHit == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp69 := range v.ThingJustHit {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingJustHit[tmp69]))
	}
	if !w.collection(len(v.ThingSkullFly), v.ThingSkullFly == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp70 := range v.ThingSkullFly {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingSkullFly[tmp70]))
	}
	if !w.collection(len(v.ThingResumeChaseNow), v.ThingResumeChaseNow == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp71 := range v.ThingResumeChaseNow {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingResumeChaseNow[tmp71]))
	}
	if !w.collection(len(v.ThingReactionTics), v.ThingReactionTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp72 := range v.ThingReactionTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingReactionTics[tmp72]))
	}
	if !w.collection(len(v.ThingWakeTics), v.ThingWakeTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp73 := range v.ThingWakeTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingWakeTics[tmp73]))
	}
	if !w.collection(len(v.ThingLastLook), v.ThingLastLook == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp74 := range v.ThingLastLook {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingLastLook[tmp74]))
	}
	if !w.collection(len(v.ThingDead), v.ThingDead == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp75 := range v.ThingDead {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingDead[tmp75]))
	}
	if !w.collection(len(v.ThingAmbush), v.ThingAmbush == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp76 := range v.ThingAmbush {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingAmbush[tmp76]))
	}
	if !w.collection(len(v.ThingInFloat), v.ThingInFloat == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp77 := range v.ThingInFloat {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingInFloat[tmp77]))
	}
	if !w.collection(len(v.ThingGibbed), v.ThingGibbed == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp78 := range v.ThingGibbed {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingGibbed[tmp78]))
	}
	if !w.collection(len(v.ThingGibTick), v.ThingGibTick == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp79 := range v.ThingGibTick {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingGibTick[tmp79]))
	}
	if !w.collection(len(v.ThingXDeath), v.ThingXDeath == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp80 := range v.ThingXDeath {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.ThingXDeath[tmp80]))
	}
	if !w.collection(len(v.ThingDeathTics), v.ThingDeathTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp81 := range v.ThingDeathTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingDeathTics[tmp81]))
	}
	if !w.collection(len(v.ThingAttackTics), v.ThingAttackTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp82 := range v.ThingAttackTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingAttackTics[tmp82]))
	}
	if !w.collection(len(v.ThingAttackPhase), v.ThingAttackPhase == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp83 := range v.ThingAttackPhase {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingAttackPhase[tmp83]))
	}
	if !w.collection(len(v.ThingAttackFireTics), v.ThingAttackFireTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp84 := range v.ThingAttackFireTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingAttackFireTics[tmp84]))
	}
	if !w.collection(len(v.ThingPainTics), v.ThingPainTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp85 := range v.ThingPainTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingPainTics[tmp85]))
	}
	if !w.collection(len(v.ThingThinkWait), v.ThingThinkWait == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp86 := range v.ThingThinkWait {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingThinkWait[tmp86]))
	}
	if !w.collection(len(v.ThingDoomState), v.ThingDoomState == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp87 := range v.ThingDoomState {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingDoomState[tmp87]))
	}
	if !w.collection(len(v.ThingState), v.ThingState == nil, authorityBinarySizeOf[uint8]()) {
		return
	}
	w.raw(v.ThingState[:])
	if !w.collection(len(v.ThingStateTics), v.ThingStateTics == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp88 := range v.ThingStateTics {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingStateTics[tmp88]))
	}
	if !w.collection(len(v.ThingStatePhase), v.ThingStatePhase == nil, authorityBinarySizeOf[int]()) {
		return
	}
	for tmp89 := range v.ThingStatePhase {
		if w.err != nil {
			return
		}
		w.signed(int64(v.ThingStatePhase[tmp89]))
	}
	if !w.collection(len(v.BossSpawnCubes), v.BossSpawnCubes == nil, authorityBinarySizeOf[bossSpawnCubeSaveState]()) {
		return
	}
	for tmp90 := range v.BossSpawnCubes {
		if w.err != nil {
			return
		}
		w.writedoomruntime_bossSpawnCubeSaveState(&v.BossSpawnCubes[tmp90])
	}
	if !w.collection(len(v.BossSpawnFires), v.BossSpawnFires == nil, authorityBinarySizeOf[bossSpawnFireSaveState]()) {
		return
	}
	for tmp91 := range v.BossSpawnFires {
		if w.err != nil {
			return
		}
		w.writedoomruntime_bossSpawnFireSaveState(&v.BossSpawnFires[tmp91])
	}
	w.signed(int64(v.BossBrainTargetOrder))
	w.boolean(bool(v.BossBrainEasyToggle))
	if !w.collection(len(v.Projectiles), v.Projectiles == nil, authorityBinarySizeOf[projectileSaveState]()) {
		return
	}
	for tmp92 := range v.Projectiles {
		if w.err != nil {
			return
		}
		w.writedoomruntime_projectileSaveState(&v.Projectiles[tmp92])
	}
	if !w.collection(len(v.ProjectileImpacts), v.ProjectileImpacts == nil, authorityBinarySizeOf[projectileImpactSaveState]()) {
		return
	}
	for tmp93 := range v.ProjectileImpacts {
		if w.err != nil {
			return
		}
		w.writedoomruntime_projectileImpactSaveState(&v.ProjectileImpacts[tmp93])
	}
	if !w.collection(len(v.HitscanPuffs), v.HitscanPuffs == nil, authorityBinarySizeOf[hitscanPuffSaveState]()) {
		return
	}
	for tmp94 := range v.HitscanPuffs {
		if w.err != nil {
			return
		}
		w.writedoomruntime_hitscanPuffSaveState(&v.HitscanPuffs[tmp94])
	}
	w.signed(int64(v.CheatLevel))
	w.boolean(bool(v.Invulnerable))
	w.boolean(bool(v.NoClip))
	w.writedoomruntime_playerInventorySaveState(&v.Inventory)
	w.signed(int64(v.LastAttackRange))
	w.boolean(bool(v.AlwaysRun))
	w.boolean(bool(v.AutoWeaponSwitch))
	w.boolean(bool(v.WeaponRefire))
	w.boolean(bool(v.WeaponAttackDown))
	w.signed(int64(v.WeaponState))
	w.signed(int64(v.WeaponStateTics))
	w.signed(int64(v.WeaponFlashState))
	w.signed(int64(v.WeaponFlashTics))
	w.signed(int64(v.WeaponPSpriteY))
	w.writedoomruntime_playerStats(&v.Stats)
	w.signed(int64(v.WorldTic))
	w.signed(int64(v.LevelKillsTotal))
	w.signed(int64(v.LevelItemsTotal))
	w.signed(int64(v.PlayerKillCount))
	w.signed(int64(v.PlayerItemCount))
	w.signed(int64(v.PlayerBlockOrder))
	w.signed(int64(v.NextThinkerOrder))
	w.signed(int64(v.NextBlockmapOrder))
	if !w.collection(len(v.SecretFound), v.SecretFound == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp95 := range v.SecretFound {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.SecretFound[tmp95]))
	}
	w.signed(int64(v.SecretsFound))
	w.signed(int64(v.SecretsTotal))
	if !w.collection(len(v.SectorSoundTarget), v.SectorSoundTarget == nil, authorityBinarySizeOf[bool]()) {
		return
	}
	for tmp96 := range v.SectorSoundTarget {
		if w.err != nil {
			return
		}
		w.boolean(bool(v.SectorSoundTarget[tmp96]))
	}
	w.boolean(bool(v.IsDead))
	w.signed(int64(v.PlayerMobjHealth))
	w.signed(int64(v.DamageFlashTic))
	w.signed(int64(v.BonusFlashTic))
	if !w.collection(len(v.SectorLightFx), v.SectorLightFx == nil, authorityBinarySizeOf[sectorLightEffectSaveState]()) {
		return
	}
	for tmp97 := range v.SectorLightFx {
		if w.err != nil {
			return
		}
		w.writedoomruntime_sectorLightEffectSaveState(&v.SectorLightFx[tmp97])
	}
	if !w.collection(len(v.Things), v.Things == nil, authorityBinarySizeOf[mapdata.Thing]()) {
		return
	}
	for tmp98 := range v.Things {
		if w.err != nil {
			return
		}
		w.writemapdata_Thing(&v.Things[tmp98])
	}
	if !w.collection(len(v.Sidedefs), v.Sidedefs == nil, authorityBinarySizeOf[mapdata.Sidedef]()) {
		return
	}
	for tmp99 := range v.Sidedefs {
		if w.err != nil {
			return
		}
		w.writemapdata_Sidedef(&v.Sidedefs[tmp99])
	}
	if !w.collection(len(v.Sectors), v.Sectors == nil, authorityBinarySizeOf[mapdata.Sector]()) {
		return
	}
	for tmp100 := range v.Sectors {
		if w.err != nil {
			return
		}
		w.writemapdata_Sector(&v.Sectors[tmp100])
	}
	if !w.collection(len(v.SectorFloor), v.SectorFloor == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp101 := range v.SectorFloor {
		if w.err != nil {
			return
		}
		w.signed(int64(v.SectorFloor[tmp101]))
	}
	if !w.collection(len(v.SectorCeil), v.SectorCeil == nil, authorityBinarySizeOf[int64]()) {
		return
	}
	for tmp102 := range v.SectorCeil {
		if w.err != nil {
			return
		}
		w.signed(int64(v.SectorCeil[tmp102]))
	}
	if !w.collection(len(v.LineSpecial), v.LineSpecial == nil, authorityBinarySizeOf[uint16]()) {
		return
	}
	for tmp103 := range v.LineSpecial {
		if w.err != nil {
			return
		}
		w.unsigned(uint64(v.LineSpecial[tmp103]))
	}
	if !w.collection(len(v.Doors), v.Doors == nil, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[doorThinkerSaveState]()+16)) {
		return
	}
	tmp104 := make([]int, 0, len(v.Doors))
	for tmp105 := range v.Doors {
		tmp104 = append(tmp104, tmp105)
	}
	slices.Sort(tmp104)
	for _, tmp105 := range tmp104 {
		if w.err != nil {
			return
		}
		tmp106 := v.Doors[tmp105]
		w.signed(int64(tmp105))
		w.writedoomruntime_doorThinkerSaveState(&tmp106)
	}
	if !w.collection(len(v.Floors), v.Floors == nil, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[floorThinkerSaveState]()+16)) {
		return
	}
	tmp107 := make([]int, 0, len(v.Floors))
	for tmp108 := range v.Floors {
		tmp107 = append(tmp107, tmp108)
	}
	slices.Sort(tmp107)
	for _, tmp108 := range tmp107 {
		if w.err != nil {
			return
		}
		tmp109 := v.Floors[tmp108]
		w.signed(int64(tmp108))
		w.writedoomruntime_floorThinkerSaveState(&tmp109)
	}
	if !w.collection(len(v.Plats), v.Plats == nil, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[platThinkerSaveState]()+16)) {
		return
	}
	tmp110 := make([]int, 0, len(v.Plats))
	for tmp111 := range v.Plats {
		tmp110 = append(tmp110, tmp111)
	}
	slices.Sort(tmp110)
	for _, tmp111 := range tmp110 {
		if w.err != nil {
			return
		}
		tmp112 := v.Plats[tmp111]
		w.signed(int64(tmp111))
		w.writedoomruntime_platThinkerSaveState(&tmp112)
	}
	if !w.collection(len(v.Ceilings), v.Ceilings == nil, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[ceilingThinkerSaveState]()+16)) {
		return
	}
	tmp113 := make([]int, 0, len(v.Ceilings))
	for tmp114 := range v.Ceilings {
		tmp113 = append(tmp113, tmp114)
	}
	slices.Sort(tmp113)
	for _, tmp114 := range tmp113 {
		if w.err != nil {
			return
		}
		tmp115 := v.Ceilings[tmp114]
		w.signed(int64(tmp114))
		w.writedoomruntime_ceilingThinkerSaveState(&tmp115)
	}
	if !w.collection(len(v.DelayedSwitchReverts), v.DelayedSwitchReverts == nil, authorityBinarySizeOf[delayedSwitchTextureSaveState]()) {
		return
	}
	for tmp116 := range v.DelayedSwitchReverts {
		if w.err != nil {
			return
		}
		w.writedoomruntime_delayedSwitchTextureSaveState(&v.DelayedSwitchReverts[tmp116])
	}
}
func (r *authorityBinaryReader) readdoomruntime_gameSaveState(v *gameSaveState) {
	if r.err != nil {
		return
	}
	r.readdoomruntime_sessionSaveState(&v.Session)
	r.readdoomruntime_playerSaveState(&v.Player)
	r.readmapview_ViewState(&v.View)
	v.Mode = int(r.signed(strconv.IntSize))
	v.RotateView = bool(r.boolean())
	v.ParityReveal = int(r.signed(strconv.IntSize))
	v.ParityIDDT = int(r.signed(strconv.IntSize))
	v.ShowGrid = bool(r.boolean())
	v.ShowLegend = bool(r.boolean())
	v.PaletteLUTEnabled = bool(r.boolean())
	v.GammaLevel = int(r.signed(strconv.IntSize))
	v.CRTEnabled = bool(r.boolean())
	v.UseFlash = int(r.signed(strconv.IntSize))
	v.UseText = string(r.string())
	v.HUDMessagesEnabled = bool(r.boolean())
	v.PrevPX = int64(r.signed(64))
	v.PrevPY = int64(r.signed(64))
	v.PrevAngle = uint32(r.unsigned(32))
	v.PlayerViewZ = int64(r.signed(64))
	tmp117, tmp118 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp118 {
		v.ThingCollected = make([]bool, tmp117)
		for tmp119 := range v.ThingCollected {
			if r.err != nil {
				return
			}
			v.ThingCollected[tmp119] = bool(r.boolean())
		}
	}
	tmp120, tmp121 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp121 {
		v.ThingDropped = make([]bool, tmp120)
		for tmp122 := range v.ThingDropped {
			if r.err != nil {
				return
			}
			v.ThingDropped[tmp122] = bool(r.boolean())
		}
	}
	tmp123, tmp124 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp124 {
		v.ThingThinkerOrder = make([]int64, tmp123)
		for tmp125 := range v.ThingThinkerOrder {
			if r.err != nil {
				return
			}
			v.ThingThinkerOrder[tmp125] = int64(r.signed(64))
		}
	}
	tmp126, tmp127 := r.collection(5, authorityBinarySizeOf[mapdata.Thing]())
	if r.err != nil {
		return
	}
	if tmp127 {
		v.ThingSpawnPoint = make([]mapdata.Thing, tmp126)
		for tmp128 := range v.ThingSpawnPoint {
			if r.err != nil {
				return
			}
			r.readmapdata_Thing(&v.ThingSpawnPoint[tmp128])
		}
	}
	tmp129, tmp130 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp130 {
		v.ThingX = make([]int64, tmp129)
		for tmp131 := range v.ThingX {
			if r.err != nil {
				return
			}
			v.ThingX[tmp131] = int64(r.signed(64))
		}
	}
	tmp132, tmp133 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp133 {
		v.ThingY = make([]int64, tmp132)
		for tmp134 := range v.ThingY {
			if r.err != nil {
				return
			}
			v.ThingY[tmp134] = int64(r.signed(64))
		}
	}
	tmp135, tmp136 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp136 {
		v.ThingMomX = make([]int64, tmp135)
		for tmp137 := range v.ThingMomX {
			if r.err != nil {
				return
			}
			v.ThingMomX[tmp137] = int64(r.signed(64))
		}
	}
	tmp138, tmp139 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp139 {
		v.ThingMomY = make([]int64, tmp138)
		for tmp140 := range v.ThingMomY {
			if r.err != nil {
				return
			}
			v.ThingMomY[tmp140] = int64(r.signed(64))
		}
	}
	tmp141, tmp142 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp142 {
		v.ThingMomZ = make([]int64, tmp141)
		for tmp143 := range v.ThingMomZ {
			if r.err != nil {
				return
			}
			v.ThingMomZ[tmp143] = int64(r.signed(64))
		}
	}
	tmp144, tmp145 := r.collection(1, authorityBinarySizeOf[uint32]())
	if r.err != nil {
		return
	}
	if tmp145 {
		v.ThingAngleState = make([]uint32, tmp144)
		for tmp146 := range v.ThingAngleState {
			if r.err != nil {
				return
			}
			v.ThingAngleState[tmp146] = uint32(r.unsigned(32))
		}
	}
	tmp147, tmp148 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp148 {
		v.ThingZState = make([]int64, tmp147)
		for tmp149 := range v.ThingZState {
			if r.err != nil {
				return
			}
			v.ThingZState[tmp149] = int64(r.signed(64))
		}
	}
	tmp150, tmp151 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp151 {
		v.ThingFloorState = make([]int64, tmp150)
		for tmp152 := range v.ThingFloorState {
			if r.err != nil {
				return
			}
			v.ThingFloorState[tmp152] = int64(r.signed(64))
		}
	}
	tmp153, tmp154 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp154 {
		v.ThingCeilState = make([]int64, tmp153)
		for tmp155 := range v.ThingCeilState {
			if r.err != nil {
				return
			}
			v.ThingCeilState[tmp155] = int64(r.signed(64))
		}
	}
	tmp156, tmp157 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp157 {
		v.ThingSupportValid = make([]bool, tmp156)
		for tmp158 := range v.ThingSupportValid {
			if r.err != nil {
				return
			}
			v.ThingSupportValid[tmp158] = bool(r.boolean())
		}
	}
	tmp159, tmp160 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp160 {
		v.ThingHP = make([]int, tmp159)
		for tmp161 := range v.ThingHP {
			if r.err != nil {
				return
			}
			v.ThingHP[tmp161] = int(r.signed(strconv.IntSize))
		}
	}
	tmp162, tmp163 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp163 {
		v.ThingAggro = make([]bool, tmp162)
		for tmp164 := range v.ThingAggro {
			if r.err != nil {
				return
			}
			v.ThingAggro[tmp164] = bool(r.boolean())
		}
	}
	tmp165, tmp166 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp166 {
		v.ThingTargetPlayer = make([]bool, tmp165)
		for tmp167 := range v.ThingTargetPlayer {
			if r.err != nil {
				return
			}
			v.ThingTargetPlayer[tmp167] = bool(r.boolean())
		}
	}
	tmp168, tmp169 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp169 {
		v.ThingTargetIdx = make([]int, tmp168)
		for tmp170 := range v.ThingTargetIdx {
			if r.err != nil {
				return
			}
			v.ThingTargetIdx[tmp170] = int(r.signed(strconv.IntSize))
		}
	}
	tmp171, tmp172 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp172 {
		v.ThingTracerFireOrder = make([]int64, tmp171)
		for tmp173 := range v.ThingTracerFireOrder {
			if r.err != nil {
				return
			}
			v.ThingTracerFireOrder[tmp173] = int64(r.signed(64))
		}
	}
	tmp174, tmp175 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp175 {
		v.ThingThreshold = make([]int, tmp174)
		for tmp176 := range v.ThingThreshold {
			if r.err != nil {
				return
			}
			v.ThingThreshold[tmp176] = int(r.signed(strconv.IntSize))
		}
	}
	tmp177, tmp178 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp178 {
		v.ThingCooldown = make([]int, tmp177)
		for tmp179 := range v.ThingCooldown {
			if r.err != nil {
				return
			}
			v.ThingCooldown[tmp179] = int(r.signed(strconv.IntSize))
		}
	}
	tmp180, tmp181 := r.collection(1, authorityBinarySizeOf[uint8]())
	if r.err != nil {
		return
	}
	if tmp181 {
		v.ThingMoveDir = make([]uint8, tmp180)
		copy(v.ThingMoveDir, r.raw(tmp180))
	}
	tmp183, tmp184 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp184 {
		v.ThingMoveCount = make([]int, tmp183)
		for tmp185 := range v.ThingMoveCount {
			if r.err != nil {
				return
			}
			v.ThingMoveCount[tmp185] = int(r.signed(strconv.IntSize))
		}
	}
	tmp186, tmp187 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp187 {
		v.ThingJustAtk = make([]bool, tmp186)
		for tmp188 := range v.ThingJustAtk {
			if r.err != nil {
				return
			}
			v.ThingJustAtk[tmp188] = bool(r.boolean())
		}
	}
	tmp189, tmp190 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp190 {
		v.ThingJustHit = make([]bool, tmp189)
		for tmp191 := range v.ThingJustHit {
			if r.err != nil {
				return
			}
			v.ThingJustHit[tmp191] = bool(r.boolean())
		}
	}
	tmp192, tmp193 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp193 {
		v.ThingSkullFly = make([]bool, tmp192)
		for tmp194 := range v.ThingSkullFly {
			if r.err != nil {
				return
			}
			v.ThingSkullFly[tmp194] = bool(r.boolean())
		}
	}
	tmp195, tmp196 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp196 {
		v.ThingResumeChaseNow = make([]bool, tmp195)
		for tmp197 := range v.ThingResumeChaseNow {
			if r.err != nil {
				return
			}
			v.ThingResumeChaseNow[tmp197] = bool(r.boolean())
		}
	}
	tmp198, tmp199 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp199 {
		v.ThingReactionTics = make([]int, tmp198)
		for tmp200 := range v.ThingReactionTics {
			if r.err != nil {
				return
			}
			v.ThingReactionTics[tmp200] = int(r.signed(strconv.IntSize))
		}
	}
	tmp201, tmp202 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp202 {
		v.ThingWakeTics = make([]int, tmp201)
		for tmp203 := range v.ThingWakeTics {
			if r.err != nil {
				return
			}
			v.ThingWakeTics[tmp203] = int(r.signed(strconv.IntSize))
		}
	}
	tmp204, tmp205 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp205 {
		v.ThingLastLook = make([]int, tmp204)
		for tmp206 := range v.ThingLastLook {
			if r.err != nil {
				return
			}
			v.ThingLastLook[tmp206] = int(r.signed(strconv.IntSize))
		}
	}
	tmp207, tmp208 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp208 {
		v.ThingDead = make([]bool, tmp207)
		for tmp209 := range v.ThingDead {
			if r.err != nil {
				return
			}
			v.ThingDead[tmp209] = bool(r.boolean())
		}
	}
	tmp210, tmp211 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp211 {
		v.ThingAmbush = make([]bool, tmp210)
		for tmp212 := range v.ThingAmbush {
			if r.err != nil {
				return
			}
			v.ThingAmbush[tmp212] = bool(r.boolean())
		}
	}
	tmp213, tmp214 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp214 {
		v.ThingInFloat = make([]bool, tmp213)
		for tmp215 := range v.ThingInFloat {
			if r.err != nil {
				return
			}
			v.ThingInFloat[tmp215] = bool(r.boolean())
		}
	}
	tmp216, tmp217 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp217 {
		v.ThingGibbed = make([]bool, tmp216)
		for tmp218 := range v.ThingGibbed {
			if r.err != nil {
				return
			}
			v.ThingGibbed[tmp218] = bool(r.boolean())
		}
	}
	tmp219, tmp220 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp220 {
		v.ThingGibTick = make([]int, tmp219)
		for tmp221 := range v.ThingGibTick {
			if r.err != nil {
				return
			}
			v.ThingGibTick[tmp221] = int(r.signed(strconv.IntSize))
		}
	}
	tmp222, tmp223 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp223 {
		v.ThingXDeath = make([]bool, tmp222)
		for tmp224 := range v.ThingXDeath {
			if r.err != nil {
				return
			}
			v.ThingXDeath[tmp224] = bool(r.boolean())
		}
	}
	tmp225, tmp226 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp226 {
		v.ThingDeathTics = make([]int, tmp225)
		for tmp227 := range v.ThingDeathTics {
			if r.err != nil {
				return
			}
			v.ThingDeathTics[tmp227] = int(r.signed(strconv.IntSize))
		}
	}
	tmp228, tmp229 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp229 {
		v.ThingAttackTics = make([]int, tmp228)
		for tmp230 := range v.ThingAttackTics {
			if r.err != nil {
				return
			}
			v.ThingAttackTics[tmp230] = int(r.signed(strconv.IntSize))
		}
	}
	tmp231, tmp232 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp232 {
		v.ThingAttackPhase = make([]int, tmp231)
		for tmp233 := range v.ThingAttackPhase {
			if r.err != nil {
				return
			}
			v.ThingAttackPhase[tmp233] = int(r.signed(strconv.IntSize))
		}
	}
	tmp234, tmp235 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp235 {
		v.ThingAttackFireTics = make([]int, tmp234)
		for tmp236 := range v.ThingAttackFireTics {
			if r.err != nil {
				return
			}
			v.ThingAttackFireTics[tmp236] = int(r.signed(strconv.IntSize))
		}
	}
	tmp237, tmp238 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp238 {
		v.ThingPainTics = make([]int, tmp237)
		for tmp239 := range v.ThingPainTics {
			if r.err != nil {
				return
			}
			v.ThingPainTics[tmp239] = int(r.signed(strconv.IntSize))
		}
	}
	tmp240, tmp241 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp241 {
		v.ThingThinkWait = make([]int, tmp240)
		for tmp242 := range v.ThingThinkWait {
			if r.err != nil {
				return
			}
			v.ThingThinkWait[tmp242] = int(r.signed(strconv.IntSize))
		}
	}
	tmp243, tmp244 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp244 {
		v.ThingDoomState = make([]int, tmp243)
		for tmp245 := range v.ThingDoomState {
			if r.err != nil {
				return
			}
			v.ThingDoomState[tmp245] = int(r.signed(strconv.IntSize))
		}
	}
	tmp246, tmp247 := r.collection(1, authorityBinarySizeOf[uint8]())
	if r.err != nil {
		return
	}
	if tmp247 {
		v.ThingState = make([]uint8, tmp246)
		copy(v.ThingState, r.raw(tmp246))
	}
	tmp249, tmp250 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp250 {
		v.ThingStateTics = make([]int, tmp249)
		for tmp251 := range v.ThingStateTics {
			if r.err != nil {
				return
			}
			v.ThingStateTics[tmp251] = int(r.signed(strconv.IntSize))
		}
	}
	tmp252, tmp253 := r.collection(1, authorityBinarySizeOf[int]())
	if r.err != nil {
		return
	}
	if tmp253 {
		v.ThingStatePhase = make([]int, tmp252)
		for tmp254 := range v.ThingStatePhase {
			if r.err != nil {
				return
			}
			v.ThingStatePhase[tmp254] = int(r.signed(strconv.IntSize))
		}
	}
	tmp255, tmp256 := r.collection(15, authorityBinarySizeOf[bossSpawnCubeSaveState]())
	if r.err != nil {
		return
	}
	if tmp256 {
		v.BossSpawnCubes = make([]bossSpawnCubeSaveState, tmp255)
		for tmp257 := range v.BossSpawnCubes {
			if r.err != nil {
				return
			}
			r.readdoomruntime_bossSpawnCubeSaveState(&v.BossSpawnCubes[tmp257])
		}
	}
	tmp258, tmp259 := r.collection(8, authorityBinarySizeOf[bossSpawnFireSaveState]())
	if r.err != nil {
		return
	}
	if tmp259 {
		v.BossSpawnFires = make([]bossSpawnFireSaveState, tmp258)
		for tmp260 := range v.BossSpawnFires {
			if r.err != nil {
				return
			}
			r.readdoomruntime_bossSpawnFireSaveState(&v.BossSpawnFires[tmp260])
		}
	}
	v.BossBrainTargetOrder = int(r.signed(strconv.IntSize))
	v.BossBrainEasyToggle = bool(r.boolean())
	tmp261, tmp262 := r.collection(30, authorityBinarySizeOf[projectileSaveState]())
	if r.err != nil {
		return
	}
	if tmp262 {
		v.Projectiles = make([]projectileSaveState, tmp261)
		for tmp263 := range v.Projectiles {
			if r.err != nil {
				return
			}
			r.readdoomruntime_projectileSaveState(&v.Projectiles[tmp263])
		}
	}
	tmp264, tmp265 := r.collection(20, authorityBinarySizeOf[projectileImpactSaveState]())
	if r.err != nil {
		return
	}
	if tmp265 {
		v.ProjectileImpacts = make([]projectileImpactSaveState, tmp264)
		for tmp266 := range v.ProjectileImpacts {
			if r.err != nil {
				return
			}
			r.readdoomruntime_projectileImpactSaveState(&v.ProjectileImpacts[tmp266])
		}
	}
	tmp267, tmp268 := r.collection(15, authorityBinarySizeOf[hitscanPuffSaveState]())
	if r.err != nil {
		return
	}
	if tmp268 {
		v.HitscanPuffs = make([]hitscanPuffSaveState, tmp267)
		for tmp269 := range v.HitscanPuffs {
			if r.err != nil {
				return
			}
			r.readdoomruntime_hitscanPuffSaveState(&v.HitscanPuffs[tmp269])
		}
	}
	v.CheatLevel = int(r.signed(strconv.IntSize))
	v.Invulnerable = bool(r.boolean())
	v.NoClip = bool(r.boolean())
	r.readdoomruntime_playerInventorySaveState(&v.Inventory)
	v.LastAttackRange = int64(r.signed(64))
	v.AlwaysRun = bool(r.boolean())
	v.AutoWeaponSwitch = bool(r.boolean())
	v.WeaponRefire = bool(r.boolean())
	v.WeaponAttackDown = bool(r.boolean())
	v.WeaponState = int(r.signed(strconv.IntSize))
	v.WeaponStateTics = int(r.signed(strconv.IntSize))
	v.WeaponFlashState = int(r.signed(strconv.IntSize))
	v.WeaponFlashTics = int(r.signed(strconv.IntSize))
	v.WeaponPSpriteY = int(r.signed(strconv.IntSize))
	r.readdoomruntime_playerStats(&v.Stats)
	v.WorldTic = int(r.signed(strconv.IntSize))
	v.LevelKillsTotal = int(r.signed(strconv.IntSize))
	v.LevelItemsTotal = int(r.signed(strconv.IntSize))
	v.PlayerKillCount = int(r.signed(strconv.IntSize))
	v.PlayerItemCount = int(r.signed(strconv.IntSize))
	v.PlayerBlockOrder = int64(r.signed(64))
	v.NextThinkerOrder = int64(r.signed(64))
	v.NextBlockmapOrder = int64(r.signed(64))
	tmp270, tmp271 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp271 {
		v.SecretFound = make([]bool, tmp270)
		for tmp272 := range v.SecretFound {
			if r.err != nil {
				return
			}
			v.SecretFound[tmp272] = bool(r.boolean())
		}
	}
	v.SecretsFound = int(r.signed(strconv.IntSize))
	v.SecretsTotal = int(r.signed(strconv.IntSize))
	tmp273, tmp274 := r.collection(1, authorityBinarySizeOf[bool]())
	if r.err != nil {
		return
	}
	if tmp274 {
		v.SectorSoundTarget = make([]bool, tmp273)
		for tmp275 := range v.SectorSoundTarget {
			if r.err != nil {
				return
			}
			v.SectorSoundTarget[tmp275] = bool(r.boolean())
		}
	}
	v.IsDead = bool(r.boolean())
	v.PlayerMobjHealth = int(r.signed(strconv.IntSize))
	v.DamageFlashTic = int(r.signed(strconv.IntSize))
	v.BonusFlashTic = int(r.signed(strconv.IntSize))
	tmp276, tmp277 := r.collection(10, authorityBinarySizeOf[sectorLightEffectSaveState]())
	if r.err != nil {
		return
	}
	if tmp277 {
		v.SectorLightFx = make([]sectorLightEffectSaveState, tmp276)
		for tmp278 := range v.SectorLightFx {
			if r.err != nil {
				return
			}
			r.readdoomruntime_sectorLightEffectSaveState(&v.SectorLightFx[tmp278])
		}
	}
	tmp279, tmp280 := r.collection(5, authorityBinarySizeOf[mapdata.Thing]())
	if r.err != nil {
		return
	}
	if tmp280 {
		v.Things = make([]mapdata.Thing, tmp279)
		for tmp281 := range v.Things {
			if r.err != nil {
				return
			}
			r.readmapdata_Thing(&v.Things[tmp281])
		}
	}
	tmp282, tmp283 := r.collection(6, authorityBinarySizeOf[mapdata.Sidedef]())
	if r.err != nil {
		return
	}
	if tmp283 {
		v.Sidedefs = make([]mapdata.Sidedef, tmp282)
		for tmp284 := range v.Sidedefs {
			if r.err != nil {
				return
			}
			r.readmapdata_Sidedef(&v.Sidedefs[tmp284])
		}
	}
	tmp285, tmp286 := r.collection(7, authorityBinarySizeOf[mapdata.Sector]())
	if r.err != nil {
		return
	}
	if tmp286 {
		v.Sectors = make([]mapdata.Sector, tmp285)
		for tmp287 := range v.Sectors {
			if r.err != nil {
				return
			}
			r.readmapdata_Sector(&v.Sectors[tmp287])
		}
	}
	tmp288, tmp289 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp289 {
		v.SectorFloor = make([]int64, tmp288)
		for tmp290 := range v.SectorFloor {
			if r.err != nil {
				return
			}
			v.SectorFloor[tmp290] = int64(r.signed(64))
		}
	}
	tmp291, tmp292 := r.collection(1, authorityBinarySizeOf[int64]())
	if r.err != nil {
		return
	}
	if tmp292 {
		v.SectorCeil = make([]int64, tmp291)
		for tmp293 := range v.SectorCeil {
			if r.err != nil {
				return
			}
			v.SectorCeil[tmp293] = int64(r.signed(64))
		}
	}
	tmp294, tmp295 := r.collection(1, authorityBinarySizeOf[uint16]())
	if r.err != nil {
		return
	}
	if tmp295 {
		v.LineSpecial = make([]uint16, tmp294)
		for tmp296 := range v.LineSpecial {
			if r.err != nil {
				return
			}
			v.LineSpecial[tmp296] = uint16(r.unsigned(16))
		}
	}
	tmp297, tmp298 := r.collection(9, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[doorThinkerSaveState]()+16))
	if r.err != nil {
		return
	}
	if tmp298 {
		v.Doors = make(map[int]doorThinkerSaveState, tmp297)
		var tmp301 int
		for tmp302 := 0; tmp302 < tmp297; tmp302++ {
			if r.err != nil {
				return
			}
			var tmp299 int
			var tmp300 doorThinkerSaveState
			tmp299 = int(r.signed(strconv.IntSize))
			if tmp302 > 0 && tmp299 <= tmp301 {
				r.fail("unordered or duplicate map key")
				return
			}
			tmp301 = tmp299
			r.readdoomruntime_doorThinkerSaveState(&tmp300)
			v.Doors[tmp299] = tmp300
		}
	}
	tmp303, tmp304 := r.collection(9, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[floorThinkerSaveState]()+16))
	if r.err != nil {
		return
	}
	if tmp304 {
		v.Floors = make(map[int]floorThinkerSaveState, tmp303)
		var tmp307 int
		for tmp308 := 0; tmp308 < tmp303; tmp308++ {
			if r.err != nil {
				return
			}
			var tmp305 int
			var tmp306 floorThinkerSaveState
			tmp305 = int(r.signed(strconv.IntSize))
			if tmp308 > 0 && tmp305 <= tmp307 {
				r.fail("unordered or duplicate map key")
				return
			}
			tmp307 = tmp305
			r.readdoomruntime_floorThinkerSaveState(&tmp306)
			v.Floors[tmp305] = tmp306
		}
	}
	tmp309, tmp310 := r.collection(13, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[platThinkerSaveState]()+16))
	if r.err != nil {
		return
	}
	if tmp310 {
		v.Plats = make(map[int]platThinkerSaveState, tmp309)
		var tmp313 int
		for tmp314 := 0; tmp314 < tmp309; tmp314++ {
			if r.err != nil {
				return
			}
			var tmp311 int
			var tmp312 platThinkerSaveState
			tmp311 = int(r.signed(strconv.IntSize))
			if tmp314 > 0 && tmp311 <= tmp313 {
				r.fail("unordered or duplicate map key")
				return
			}
			tmp313 = tmp311
			r.readdoomruntime_platThinkerSaveState(&tmp312)
			v.Plats[tmp311] = tmp312
		}
	}
	tmp315, tmp316 := r.collection(10, 2*(authorityBinarySizeOf[int]()+authorityBinarySizeOf[ceilingThinkerSaveState]()+16))
	if r.err != nil {
		return
	}
	if tmp316 {
		v.Ceilings = make(map[int]ceilingThinkerSaveState, tmp315)
		var tmp319 int
		for tmp320 := 0; tmp320 < tmp315; tmp320++ {
			if r.err != nil {
				return
			}
			var tmp317 int
			var tmp318 ceilingThinkerSaveState
			tmp317 = int(r.signed(strconv.IntSize))
			if tmp320 > 0 && tmp317 <= tmp319 {
				r.fail("unordered or duplicate map key")
				return
			}
			tmp319 = tmp317
			r.readdoomruntime_ceilingThinkerSaveState(&tmp318)
			v.Ceilings[tmp317] = tmp318
		}
	}
	tmp321, tmp322 := r.collection(6, authorityBinarySizeOf[delayedSwitchTextureSaveState]())
	if r.err != nil {
		return
	}
	if tmp322 {
		v.DelayedSwitchReverts = make([]delayedSwitchTextureSaveState, tmp321)
		for tmp323 := range v.DelayedSwitchReverts {
			if r.err != nil {
				return
			}
			r.readdoomruntime_delayedSwitchTextureSaveState(&v.DelayedSwitchReverts[tmp323])
		}
	}
}
func (w *authorityBinaryWriter) writedoomruntime_hitscanPuffSaveState(v *hitscanPuffSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Z))
	w.signed(int64(v.MomX))
	w.signed(int64(v.MomY))
	w.signed(int64(v.MomZ))
	w.signed(int64(v.FloorZ))
	w.signed(int64(v.CeilZ))
	w.signed(int64(v.LastLook))
	w.signed(int64(v.Tics))
	w.signed(int64(v.State))
	w.signed(int64(v.TotalTic))
	w.byte(byte(v.Kind))
	w.boolean(bool(v.Hidden))
	w.signed(int64(v.Order))
}
func (r *authorityBinaryReader) readdoomruntime_hitscanPuffSaveState(v *hitscanPuffSaveState) {
	if r.err != nil {
		return
	}
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.Z = int64(r.signed(64))
	v.MomX = int64(r.signed(64))
	v.MomY = int64(r.signed(64))
	v.MomZ = int64(r.signed(64))
	v.FloorZ = int64(r.signed(64))
	v.CeilZ = int64(r.signed(64))
	v.LastLook = int(r.signed(strconv.IntSize))
	v.Tics = int(r.signed(strconv.IntSize))
	v.State = int(r.signed(strconv.IntSize))
	v.TotalTic = int(r.signed(strconv.IntSize))
	v.Kind = uint8(r.byte())
	v.Hidden = bool(r.boolean())
	v.Order = int64(r.signed(64))
}
func (w *authorityBinaryWriter) writedoomruntime_platThinkerSaveState(v *platThinkerSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.signed(int64(v.Sector))
	w.byte(byte(v.Type))
	w.byte(byte(v.Status))
	w.byte(byte(v.OldStatus))
	w.signed(int64(v.Speed))
	w.signed(int64(v.Low))
	w.signed(int64(v.High))
	w.signed(int64(v.Wait))
	w.signed(int64(v.Count))
	w.string(string(v.FinishFlat))
	w.signed(int64(v.FinishSpecial))
}
func (r *authorityBinaryReader) readdoomruntime_platThinkerSaveState(v *platThinkerSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.Sector = int(r.signed(strconv.IntSize))
	v.Type = uint8(r.byte())
	v.Status = uint8(r.byte())
	v.OldStatus = uint8(r.byte())
	v.Speed = int64(r.signed(64))
	v.Low = int64(r.signed(64))
	v.High = int64(r.signed(64))
	v.Wait = int(r.signed(strconv.IntSize))
	v.Count = int(r.signed(strconv.IntSize))
	v.FinishFlat = string(r.string())
	v.FinishSpecial = int16(r.signed(16))
}
func (w *authorityBinaryWriter) writedoomruntime_playerInventorySaveState(v *playerInventorySaveState) {
	if w.err != nil {
		return
	}
	w.boolean(bool(v.BlueKey))
	w.boolean(bool(v.RedKey))
	w.boolean(bool(v.YellowKey))
	w.boolean(bool(v.Backpack))
	w.boolean(bool(v.Strength))
	w.signed(int64(v.StrengthCount))
	w.signed(int64(v.InvulnTics))
	w.signed(int64(v.InvisTics))
	w.signed(int64(v.RadSuitTics))
	w.boolean(bool(v.AllMap))
	w.signed(int64(v.LightAmpTics))
	w.signed(int64(v.ReadyWeapon))
	w.signed(int64(v.PendingWeapon))
	if !w.collection(len(v.Weapons), v.Weapons == nil, 2*(authorityBinarySizeOf[int16]()+authorityBinarySizeOf[bool]()+16)) {
		return
	}
	tmp324 := make([]int16, 0, len(v.Weapons))
	for tmp325 := range v.Weapons {
		tmp324 = append(tmp324, tmp325)
	}
	slices.Sort(tmp324)
	for _, tmp325 := range tmp324 {
		if w.err != nil {
			return
		}
		tmp326 := v.Weapons[tmp325]
		w.signed(int64(tmp325))
		w.boolean(bool(tmp326))
	}
}
func (r *authorityBinaryReader) readdoomruntime_playerInventorySaveState(v *playerInventorySaveState) {
	if r.err != nil {
		return
	}
	v.BlueKey = bool(r.boolean())
	v.RedKey = bool(r.boolean())
	v.YellowKey = bool(r.boolean())
	v.Backpack = bool(r.boolean())
	v.Strength = bool(r.boolean())
	v.StrengthCount = int(r.signed(strconv.IntSize))
	v.InvulnTics = int(r.signed(strconv.IntSize))
	v.InvisTics = int(r.signed(strconv.IntSize))
	v.RadSuitTics = int(r.signed(strconv.IntSize))
	v.AllMap = bool(r.boolean())
	v.LightAmpTics = int(r.signed(strconv.IntSize))
	v.ReadyWeapon = int(r.signed(strconv.IntSize))
	v.PendingWeapon = int(r.signed(strconv.IntSize))
	tmp327, tmp328 := r.collection(2, 2*(authorityBinarySizeOf[int16]()+authorityBinarySizeOf[bool]()+16))
	if r.err != nil {
		return
	}
	if tmp328 {
		v.Weapons = make(map[int16]bool, tmp327)
		var tmp331 int16
		for tmp332 := 0; tmp332 < tmp327; tmp332++ {
			if r.err != nil {
				return
			}
			var tmp329 int16
			var tmp330 bool
			tmp329 = int16(r.signed(16))
			if tmp332 > 0 && tmp329 <= tmp331 {
				r.fail("unordered or duplicate map key")
				return
			}
			tmp331 = tmp329
			tmp330 = bool(r.boolean())
			v.Weapons[tmp329] = tmp330
		}
	}
}
func (w *authorityBinaryWriter) writedoomruntime_playerSaveState(v *playerSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Z))
	w.signed(int64(v.FloorZ))
	w.signed(int64(v.CeilZ))
	w.signed(int64(v.Subsector))
	w.signed(int64(v.Sector))
	w.unsigned(uint64(v.Angle))
	w.signed(int64(v.MomX))
	w.signed(int64(v.MomY))
	w.signed(int64(v.MomZ))
	w.signed(int64(v.ReactionTime))
	w.boolean(bool(v.JustAttacked))
	w.signed(int64(v.ViewHeight))
	w.signed(int64(v.DeltaViewHeight))
}
func (r *authorityBinaryReader) readdoomruntime_playerSaveState(v *playerSaveState) {
	if r.err != nil {
		return
	}
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.Z = int64(r.signed(64))
	v.FloorZ = int64(r.signed(64))
	v.CeilZ = int64(r.signed(64))
	v.Subsector = int(r.signed(strconv.IntSize))
	v.Sector = int(r.signed(strconv.IntSize))
	v.Angle = uint32(r.unsigned(32))
	v.MomX = int64(r.signed(64))
	v.MomY = int64(r.signed(64))
	v.MomZ = int64(r.signed(64))
	v.ReactionTime = int(r.signed(strconv.IntSize))
	v.JustAttacked = bool(r.boolean())
	v.ViewHeight = int64(r.signed(64))
	v.DeltaViewHeight = int64(r.signed(64))
}
func (w *authorityBinaryWriter) writedoomruntime_playerStats(v *playerStats) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Health))
	w.signed(int64(v.Armor))
	w.signed(int64(v.ArmorType))
	w.signed(int64(v.Bullets))
	w.signed(int64(v.Shells))
	w.signed(int64(v.Rockets))
	w.signed(int64(v.Cells))
}
func (r *authorityBinaryReader) readdoomruntime_playerStats(v *playerStats) {
	if r.err != nil {
		return
	}
	v.Health = int(r.signed(strconv.IntSize))
	v.Armor = int(r.signed(strconv.IntSize))
	v.ArmorType = int(r.signed(strconv.IntSize))
	v.Bullets = int(r.signed(strconv.IntSize))
	v.Shells = int(r.signed(strconv.IntSize))
	v.Rockets = int(r.signed(strconv.IntSize))
	v.Cells = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_projectileImpactSaveState(v *projectileImpactSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Subsector))
	w.signed(int64(v.Order))
	w.signed(int64(v.Phase))
	w.signed(int64(v.PhaseTics))
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Z))
	w.signed(int64(v.FloorZ))
	w.signed(int64(v.CeilZ))
	w.signed(int64(v.Kind))
	w.signed(int64(v.SourceThing))
	w.signed(int64(v.SourceType))
	w.boolean(bool(v.SourcePlayer))
	w.signed(int64(v.FireTargetThing))
	w.boolean(bool(v.FireTargetPlayer))
	w.signed(int64(v.LastLook))
	w.signed(int64(v.Tics))
	w.signed(int64(v.TotalTics))
	w.unsigned(uint64(v.Angle))
	w.boolean(bool(v.SprayDone))
}
func (r *authorityBinaryReader) readdoomruntime_projectileImpactSaveState(v *projectileImpactSaveState) {
	if r.err != nil {
		return
	}
	v.Subsector = int(r.signed(strconv.IntSize))
	v.Order = int64(r.signed(64))
	v.Phase = int(r.signed(strconv.IntSize))
	v.PhaseTics = int(r.signed(strconv.IntSize))
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.Z = int64(r.signed(64))
	v.FloorZ = int64(r.signed(64))
	v.CeilZ = int64(r.signed(64))
	v.Kind = int(r.signed(strconv.IntSize))
	v.SourceThing = int(r.signed(strconv.IntSize))
	v.SourceType = int16(r.signed(16))
	v.SourcePlayer = bool(r.boolean())
	v.FireTargetThing = int(r.signed(strconv.IntSize))
	v.FireTargetPlayer = bool(r.boolean())
	v.LastLook = int(r.signed(strconv.IntSize))
	v.Tics = int(r.signed(strconv.IntSize))
	v.TotalTics = int(r.signed(strconv.IntSize))
	v.Angle = uint32(r.unsigned(32))
	v.SprayDone = bool(r.boolean())
}
func (w *authorityBinaryWriter) writedoomruntime_projectileSaveState(v *projectileSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Subsector))
	w.signed(int64(v.Order))
	w.signed(int64(v.PrevX))
	w.signed(int64(v.PrevY))
	w.signed(int64(v.PrevZ))
	w.signed(int64(v.LastLook))
	w.signed(int64(v.Frame))
	w.signed(int64(v.FrameTics))
	w.boolean(bool(v.DeferredTick))
	w.boolean(bool(v.SpawnPrev))
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Z))
	w.signed(int64(v.VX))
	w.signed(int64(v.VY))
	w.signed(int64(v.VZ))
	w.signed(int64(v.FloorZ))
	w.signed(int64(v.CeilZ))
	w.signed(int64(v.Radius))
	w.signed(int64(v.Height))
	w.signed(int64(v.TTL))
	w.signed(int64(v.SourceX))
	w.signed(int64(v.SourceY))
	w.signed(int64(v.SourceThing))
	w.signed(int64(v.SourceType))
	w.boolean(bool(v.SourcePlayer))
	w.boolean(bool(v.TracerPlayer))
	w.signed(int64(v.TracerThingTarget))
	w.unsigned(uint64(v.Angle))
	w.signed(int64(v.Kind))
}
func (r *authorityBinaryReader) readdoomruntime_projectileSaveState(v *projectileSaveState) {
	if r.err != nil {
		return
	}
	v.Subsector = int(r.signed(strconv.IntSize))
	v.Order = int64(r.signed(64))
	v.PrevX = int64(r.signed(64))
	v.PrevY = int64(r.signed(64))
	v.PrevZ = int64(r.signed(64))
	v.LastLook = int(r.signed(strconv.IntSize))
	v.Frame = int(r.signed(strconv.IntSize))
	v.FrameTics = int(r.signed(strconv.IntSize))
	v.DeferredTick = bool(r.boolean())
	v.SpawnPrev = bool(r.boolean())
	v.X = int64(r.signed(64))
	v.Y = int64(r.signed(64))
	v.Z = int64(r.signed(64))
	v.VX = int64(r.signed(64))
	v.VY = int64(r.signed(64))
	v.VZ = int64(r.signed(64))
	v.FloorZ = int64(r.signed(64))
	v.CeilZ = int64(r.signed(64))
	v.Radius = int64(r.signed(64))
	v.Height = int64(r.signed(64))
	v.TTL = int(r.signed(strconv.IntSize))
	v.SourceX = int64(r.signed(64))
	v.SourceY = int64(r.signed(64))
	v.SourceThing = int(r.signed(strconv.IntSize))
	v.SourceType = int16(r.signed(16))
	v.SourcePlayer = bool(r.boolean())
	v.TracerPlayer = bool(r.boolean())
	v.TracerThingTarget = int(r.signed(strconv.IntSize))
	v.Angle = uint32(r.unsigned(32))
	v.Kind = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_replicaImpactPlayers(v *replicaImpactPlayers) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.SourceSlot))
	w.signed(int64(v.FireTargetSlot))
	w.unsigned(uint64(v.SourceGeneration))
	w.unsigned(uint64(v.FireTargetGeneration))
}
func (r *authorityBinaryReader) readdoomruntime_replicaImpactPlayers(v *replicaImpactPlayers) {
	if r.err != nil {
		return
	}
	v.SourceSlot = int(r.signed(strconv.IntSize))
	v.FireTargetSlot = int(r.signed(strconv.IntSize))
	v.SourceGeneration = uint32(r.unsigned(32))
	v.FireTargetGeneration = uint32(r.unsigned(32))
}
func (w *authorityBinaryWriter) writedoomruntime_replicaMoveCommand(v *replicaMoveCommand) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Forward))
	w.signed(int64(v.Side))
	w.signed(int64(v.TurnRaw))
	w.signed(int64(v.Turn))
	w.signed(int64(v.WeaponSlot))
	w.boolean(bool(v.Run))
}
func (r *authorityBinaryReader) readdoomruntime_replicaMoveCommand(v *replicaMoveCommand) {
	if r.err != nil {
		return
	}
	v.Forward = int64(r.signed(64))
	v.Side = int64(r.signed(64))
	v.TurnRaw = int64(r.signed(64))
	v.Turn = int(r.signed(strconv.IntSize))
	v.WeaponSlot = int(r.signed(strconv.IntSize))
	v.Run = bool(r.boolean())
}
func (w *authorityBinaryWriter) writedoomruntime_replicaProjectilePlayers(v *replicaProjectilePlayers) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.SourceSlot))
	w.signed(int64(v.TracerSlot))
	w.unsigned(uint64(v.SourceGeneration))
	w.unsigned(uint64(v.TracerGeneration))
}
func (r *authorityBinaryReader) readdoomruntime_replicaProjectilePlayers(v *replicaProjectilePlayers) {
	if r.err != nil {
		return
	}
	v.SourceSlot = int(r.signed(strconv.IntSize))
	v.TracerSlot = int(r.signed(strconv.IntSize))
	v.SourceGeneration = uint32(r.unsigned(32))
	v.TracerGeneration = uint32(r.unsigned(32))
}
func (w *authorityBinaryWriter) writedoomruntime_sectorLightEffectSaveState(v *sectorLightEffectSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.Order))
	w.byte(byte(v.Kind))
	w.signed(int64(v.MinLight))
	w.signed(int64(v.MaxLight))
	w.signed(int64(v.Count))
	w.signed(int64(v.MinTime))
	w.signed(int64(v.MaxTime))
	w.signed(int64(v.DarkTime))
	w.signed(int64(v.BrightTime))
	w.signed(int64(v.Direction))
}
func (r *authorityBinaryReader) readdoomruntime_sectorLightEffectSaveState(v *sectorLightEffectSaveState) {
	if r.err != nil {
		return
	}
	v.Order = int64(r.signed(64))
	v.Kind = uint8(r.byte())
	v.MinLight = int16(r.signed(16))
	v.MaxLight = int16(r.signed(16))
	v.Count = int(r.signed(strconv.IntSize))
	v.MinTime = int(r.signed(strconv.IntSize))
	v.MaxTime = int(r.signed(strconv.IntSize))
	v.DarkTime = int(r.signed(strconv.IntSize))
	v.BrightTime = int(r.signed(strconv.IntSize))
	v.Direction = int(r.signed(strconv.IntSize))
}
func (w *authorityBinaryWriter) writedoomruntime_sessionSaveState(v *sessionSaveState) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.PlayerSlot))
	w.signed(int64(v.SkillLevel))
	w.string(string(v.GameMode))
	w.boolean(bool(v.ShowNoSkillItems))
	w.boolean(bool(v.ShowAllItems))
	w.boolean(bool(v.FastMonsters))
	w.boolean(bool(v.RespawnMonsters))
	w.boolean(bool(v.NoMonsters))
}
func (r *authorityBinaryReader) readdoomruntime_sessionSaveState(v *sessionSaveState) {
	if r.err != nil {
		return
	}
	v.PlayerSlot = int(r.signed(strconv.IntSize))
	v.SkillLevel = int(r.signed(strconv.IntSize))
	v.GameMode = string(r.string())
	v.ShowNoSkillItems = bool(r.boolean())
	v.ShowAllItems = bool(r.boolean())
	v.FastMonsters = bool(r.boolean())
	v.RespawnMonsters = bool(r.boolean())
	v.NoMonsters = bool(r.boolean())
}
func (w *authorityBinaryWriter) writemapdata_KeyRing(v *mapdata.KeyRing) {
	if w.err != nil {
		return
	}
	w.boolean(bool(v.Blue))
	w.boolean(bool(v.Red))
	w.boolean(bool(v.Yellow))
}
func (r *authorityBinaryReader) readmapdata_KeyRing(v *mapdata.KeyRing) {
	if r.err != nil {
		return
	}
	v.Blue = bool(r.boolean())
	v.Red = bool(r.boolean())
	v.Yellow = bool(r.boolean())
}
func (w *authorityBinaryWriter) writemapdata_Sector(v *mapdata.Sector) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.FloorHeight))
	w.signed(int64(v.CeilingHeight))
	w.string(string(v.FloorPic))
	w.string(string(v.CeilingPic))
	w.signed(int64(v.Light))
	w.signed(int64(v.Special))
	w.signed(int64(v.Tag))
}
func (r *authorityBinaryReader) readmapdata_Sector(v *mapdata.Sector) {
	if r.err != nil {
		return
	}
	v.FloorHeight = int16(r.signed(16))
	v.CeilingHeight = int16(r.signed(16))
	v.FloorPic = string(r.string())
	v.CeilingPic = string(r.string())
	v.Light = int16(r.signed(16))
	v.Special = int16(r.signed(16))
	v.Tag = int16(r.signed(16))
}
func (w *authorityBinaryWriter) writemapdata_Sidedef(v *mapdata.Sidedef) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.TextureOffset))
	w.signed(int64(v.RowOffset))
	w.string(string(v.Top))
	w.string(string(v.Bottom))
	w.string(string(v.Mid))
	w.unsigned(uint64(v.Sector))
}
func (r *authorityBinaryReader) readmapdata_Sidedef(v *mapdata.Sidedef) {
	if r.err != nil {
		return
	}
	v.TextureOffset = int16(r.signed(16))
	v.RowOffset = int16(r.signed(16))
	v.Top = string(r.string())
	v.Bottom = string(r.string())
	v.Mid = string(r.string())
	v.Sector = uint16(r.unsigned(16))
}
func (w *authorityBinaryWriter) writemapdata_Thing(v *mapdata.Thing) {
	if w.err != nil {
		return
	}
	w.signed(int64(v.X))
	w.signed(int64(v.Y))
	w.signed(int64(v.Angle))
	w.signed(int64(v.Type))
	w.signed(int64(v.Flags))
}
func (r *authorityBinaryReader) readmapdata_Thing(v *mapdata.Thing) {
	if r.err != nil {
		return
	}
	v.X = int16(r.signed(16))
	v.Y = int16(r.signed(16))
	v.Angle = int16(r.signed(16))
	v.Type = int16(r.signed(16))
	v.Flags = int16(r.signed(16))
}
func (w *authorityBinaryWriter) writemapview_SavedView(v *mapview.SavedView) {
	if w.err != nil {
		return
	}
	w.float64(float64(v.CamX))
	w.float64(float64(v.CamY))
	w.float64(float64(v.Zoom))
	w.boolean(bool(v.Follow))
	w.boolean(bool(v.Valid))
}
func (r *authorityBinaryReader) readmapview_SavedView(v *mapview.SavedView) {
	if r.err != nil {
		return
	}
	v.CamX = float64(r.float64())
	v.CamY = float64(r.float64())
	v.Zoom = float64(r.float64())
	v.Follow = bool(r.boolean())
	v.Valid = bool(r.boolean())
}
func (w *authorityBinaryWriter) writemapview_ViewState(v *mapview.ViewState) {
	if w.err != nil {
		return
	}
	w.float64(float64(v.CamX))
	w.float64(float64(v.CamY))
	w.float64(float64(v.Zoom))
	w.float64(float64(v.FitZoom))
	w.boolean(bool(v.FollowMode))
	w.writemapview_SavedView(&v.SavedView)
	w.float64(float64(v.PrevCamX))
	w.float64(float64(v.PrevCamY))
	w.float64(float64(v.RenderCamX))
	w.float64(float64(v.RenderCamY))
}
func (r *authorityBinaryReader) readmapview_ViewState(v *mapview.ViewState) {
	if r.err != nil {
		return
	}
	v.CamX = float64(r.float64())
	v.CamY = float64(r.float64())
	v.Zoom = float64(r.float64())
	v.FitZoom = float64(r.float64())
	v.FollowMode = bool(r.boolean())
	r.readmapview_SavedView(&v.SavedView)
	v.PrevCamX = float64(r.float64())
	v.PrevCamY = float64(r.float64())
	v.RenderCamX = float64(r.float64())
	v.RenderCamY = float64(r.float64())
}
func validateAuthorityThingShapes(s *gameSaveState, n int) error {
	if l := len(s.ThingCollected); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingCollected shape mismatch")
	}
	if l := len(s.ThingDropped); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingDropped shape mismatch")
	}
	if l := len(s.ThingThinkerOrder); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingThinkerOrder shape mismatch")
	}
	if l := len(s.ThingSpawnPoint); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingSpawnPoint shape mismatch")
	}
	if l := len(s.ThingX); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingX shape mismatch")
	}
	if l := len(s.ThingY); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingY shape mismatch")
	}
	if l := len(s.ThingMomX); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingMomX shape mismatch")
	}
	if l := len(s.ThingMomY); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingMomY shape mismatch")
	}
	if l := len(s.ThingMomZ); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingMomZ shape mismatch")
	}
	if l := len(s.ThingAngleState); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingAngleState shape mismatch")
	}
	if l := len(s.ThingZState); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingZState shape mismatch")
	}
	if l := len(s.ThingFloorState); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingFloorState shape mismatch")
	}
	if l := len(s.ThingCeilState); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingCeilState shape mismatch")
	}
	if l := len(s.ThingSupportValid); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingSupportValid shape mismatch")
	}
	if l := len(s.ThingHP); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingHP shape mismatch")
	}
	if l := len(s.ThingAggro); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingAggro shape mismatch")
	}
	if l := len(s.ThingTargetPlayer); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingTargetPlayer shape mismatch")
	}
	if l := len(s.ThingTargetIdx); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingTargetIdx shape mismatch")
	}
	if l := len(s.ThingTracerFireOrder); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingTracerFireOrder shape mismatch")
	}
	if l := len(s.ThingThreshold); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingThreshold shape mismatch")
	}
	if l := len(s.ThingCooldown); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingCooldown shape mismatch")
	}
	if l := len(s.ThingMoveDir); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingMoveDir shape mismatch")
	}
	if l := len(s.ThingMoveCount); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingMoveCount shape mismatch")
	}
	if l := len(s.ThingJustAtk); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingJustAtk shape mismatch")
	}
	if l := len(s.ThingJustHit); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingJustHit shape mismatch")
	}
	if l := len(s.ThingSkullFly); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingSkullFly shape mismatch")
	}
	if l := len(s.ThingResumeChaseNow); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingResumeChaseNow shape mismatch")
	}
	if l := len(s.ThingReactionTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingReactionTics shape mismatch")
	}
	if l := len(s.ThingWakeTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingWakeTics shape mismatch")
	}
	if l := len(s.ThingLastLook); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingLastLook shape mismatch")
	}
	if l := len(s.ThingDead); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingDead shape mismatch")
	}
	if l := len(s.ThingAmbush); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingAmbush shape mismatch")
	}
	if l := len(s.ThingInFloat); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingInFloat shape mismatch")
	}
	if l := len(s.ThingGibbed); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingGibbed shape mismatch")
	}
	if l := len(s.ThingGibTick); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingGibTick shape mismatch")
	}
	if l := len(s.ThingXDeath); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingXDeath shape mismatch")
	}
	if l := len(s.ThingDeathTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingDeathTics shape mismatch")
	}
	if l := len(s.ThingAttackTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingAttackTics shape mismatch")
	}
	if l := len(s.ThingAttackPhase); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingAttackPhase shape mismatch")
	}
	if l := len(s.ThingAttackFireTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingAttackFireTics shape mismatch")
	}
	if l := len(s.ThingPainTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingPainTics shape mismatch")
	}
	if l := len(s.ThingThinkWait); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingThinkWait shape mismatch")
	}
	if l := len(s.ThingDoomState); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingDoomState shape mismatch")
	}
	if l := len(s.ThingState); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingState shape mismatch")
	}
	if l := len(s.ThingStateTics); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingStateTics shape mismatch")
	}
	if l := len(s.ThingStatePhase); l != 0 && l != n {
		return fmt.Errorf("authority baseline ThingStatePhase shape mismatch")
	}
	if l := len(s.Things); l != 0 && l != n {
		return fmt.Errorf("authority baseline Things shape mismatch")
	}
	return nil
}
func equalAuthorityInventory(a, b playerInventorySaveState) bool {
	if a.BlueKey != b.BlueKey {
		return false
	}
	if a.RedKey != b.RedKey {
		return false
	}
	if a.YellowKey != b.YellowKey {
		return false
	}
	if a.Backpack != b.Backpack {
		return false
	}
	if a.Strength != b.Strength {
		return false
	}
	if a.StrengthCount != b.StrengthCount {
		return false
	}
	if a.InvulnTics != b.InvulnTics {
		return false
	}
	if a.InvisTics != b.InvisTics {
		return false
	}
	if a.RadSuitTics != b.RadSuitTics {
		return false
	}
	if a.AllMap != b.AllMap {
		return false
	}
	if a.LightAmpTics != b.LightAmpTics {
		return false
	}
	if a.ReadyWeapon != b.ReadyWeapon {
		return false
	}
	if a.PendingWeapon != b.PendingWeapon {
		return false
	}
	if (a.Weapons == nil) != (b.Weapons == nil) || !maps.Equal(a.Weapons, b.Weapons) {
		return false
	}
	return true
}
