package doomruntime

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// Regenerate with AUTHORITY_BINARY_GENERATE=1 go test ./internal/doomruntime
// -run '^TestGenerateAuthorityBinaryCodec$' (use xvfb-run on headless Linux).
// Reflection is confined to generation and the schema drift test, never encode,
// decode, or ordinary snapshot validation.
func TestGenerateAuthorityBinaryCodec(t *testing.T) {
	if os.Getenv("AUTHORITY_BINARY_GENERATE") != "1" {
		t.Skip("set AUTHORITY_BINARY_GENERATE=1 to regenerate the typed codec")
	}
	g := newAuthorityBinaryGenerator()
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by TestGenerateAuthorityBinaryCodec; DO NOT EDIT.")
	fmt.Fprintln(&out, "package doomruntime")
	fmt.Fprintln(&out, `import ("fmt"; "maps"; "slices"; "strconv"; "gddoom/internal/mapdata"; "gddoom/internal/render/mapview")`)
	fmt.Fprintf(&out, "var authorityBinarySchemaFingerprint = [16]byte{%s}\n", g.fingerprintLiteral())
	for _, typ := range g.structs {
		name := g.name(typ)
		fmt.Fprintf(&out, "func (w *authorityBinaryWriter) write%s(v *%s) { if w.err != nil { return };\n", name, g.typeName(typ))
		for i := 0; i < typ.NumField(); i++ {
			g.write(&out, typ.Field(i).Type, "v."+typ.Field(i).Name)
		}
		fmt.Fprintln(&out, "}")
		fmt.Fprintf(&out, "func (r *authorityBinaryReader) read%s(v *%s) { if r.err != nil { return };\n", name, g.typeName(typ))
		for i := 0; i < typ.NumField(); i++ {
			g.read(&out, typ.Field(i).Type, "v."+typ.Field(i).Name)
		}
		fmt.Fprintln(&out, "}")
	}
	fmt.Fprintln(&out, "func validateAuthorityThingShapes(s *gameSaveState, n int) error {")
	st := reflect.TypeOf(gameSaveState{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if strings.HasPrefix(f.Name, "Thing") && f.Type.Kind() == reflect.Slice {
			fmt.Fprintf(&out, "if l := len(s.%s); l != 0 && l != n { return fmt.Errorf(\"authority baseline %s shape mismatch\") };\n", f.Name, f.Name)
		}
	}
	fmt.Fprintln(&out, "return nil; }")
	fmt.Fprintln(&out, "func equalAuthorityInventory(a, b playerInventorySaveState) bool {")
	inventory := reflect.TypeOf(playerInventorySaveState{})
	for i := 0; i < inventory.NumField(); i++ {
		f := inventory.Field(i)
		if f.Type.Kind() == reflect.Map {
			fmt.Fprintf(&out, "if (a.%s == nil) != (b.%s == nil) || !maps.Equal(a.%s, b.%s) { return false };\n", f.Name, f.Name, f.Name, f.Name)
		} else if f.Type.Comparable() {
			fmt.Fprintf(&out, "if a.%s != b.%s { return false };\n", f.Name, f.Name)
		} else {
			t.Fatalf("unsupported inventory comparison field %s", f.Name)
		}
	}
	fmt.Fprintln(&out, "return true; }")
	source, err := format.Source(out.Bytes())
	if err != nil {
		_ = os.WriteFile("/tmp/authority-binary-generator-failed.go", out.Bytes(), 0600)
		t.Fatal(err)
	}
	if err := os.WriteFile("authoritative_binary_generated.go", source, 0644); err != nil {
		t.Fatal(err)
	}
}

type authorityBinaryGenerator struct {
	structs []reflect.Type
	schema  string
	serial  int
}

func newAuthorityBinaryGenerator() *authorityBinaryGenerator {
	g := &authorityBinaryGenerator{}
	seen := map[reflect.Type]bool{}
	var visit func(reflect.Type)
	visit = func(t reflect.Type) {
		if seen[t] {
			return
		}
		seen[t] = true
		switch t.Kind() {
		case reflect.Struct:
			g.structs = append(g.structs, t)
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if !f.IsExported() {
					panic("unexported authority field: " + t.String() + "." + f.Name)
				}
				visit(f.Type)
			}
		case reflect.Array, reflect.Slice, reflect.Pointer:
			visit(t.Elem())
		case reflect.Map:
			visit(t.Key())
			visit(t.Elem())
		case reflect.Bool, reflect.String, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		default:
			panic("unsupported authority field type: " + t.String())
		}
	}
	visit(reflect.TypeOf(authorityReplica{}))
	sort.Slice(g.structs, func(i, j int) bool { return g.structs[i].String() < g.structs[j].String() })
	var schema strings.Builder
	fmt.Fprintln(&schema, "authority-binary-v1; canonical-uvarint; zigzag-int64; ieee-float; nil-length+1; string-intern-v1")
	for _, typ := range g.structs {
		fmt.Fprintf(&schema, "%s.%s{", typ.PkgPath(), typ.Name())
		for i := 0; i < typ.NumField(); i++ {
			f := typ.Field(i)
			fmt.Fprintf(&schema, "%s:%s:%q:%t;", f.Name, authorityBinaryTypeSchema(f.Type), string(f.Tag), f.Anonymous)
		}
		fmt.Fprintln(&schema, "}")
	}
	g.schema = schema.String()
	return g
}

func authorityBinaryTypeSchema(t reflect.Type) string {
	name := t.PkgPath() + "." + t.Name()
	switch t.Kind() {
	case reflect.Pointer:
		return "*" + authorityBinaryTypeSchema(t.Elem())
	case reflect.Slice:
		return "[]" + authorityBinaryTypeSchema(t.Elem())
	case reflect.Array:
		return fmt.Sprintf("[%d]%s", t.Len(), authorityBinaryTypeSchema(t.Elem()))
	case reflect.Map:
		return "map[" + authorityBinaryTypeSchema(t.Key()) + "]" + authorityBinaryTypeSchema(t.Elem())
	default:
		return name + ":" + t.Kind().String()
	}
}

func (g *authorityBinaryGenerator) fingerprint() [16]byte {
	h := sha256.Sum256([]byte(g.schema))
	return [16]byte(h[:16])
}

func (g *authorityBinaryGenerator) fingerprintLiteral() string {
	parts := make([]string, 16)
	for i, b := range g.fingerprint() {
		parts[i] = fmt.Sprintf("0x%02x", b)
	}
	return strings.Join(parts, ",")
}

func (g *authorityBinaryGenerator) name(t reflect.Type) string {
	return strings.ReplaceAll(t.String(), ".", "_")
}

func (g *authorityBinaryGenerator) typeName(t reflect.Type) string {
	return strings.ReplaceAll(t.String(), "doomruntime.", "")
}

func (g *authorityBinaryGenerator) local() string {
	g.serial++
	return fmt.Sprintf("tmp%d", g.serial)
}

func (g *authorityBinaryGenerator) write(out *bytes.Buffer, typ reflect.Type, expr string) {
	switch typ.Kind() {
	case reflect.Struct:
		fmt.Fprintf(out, "w.write%s(&%s);\n", g.name(typ), expr)
	case reflect.Bool:
		fmt.Fprintf(out, "w.boolean(bool(%s));\n", expr)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		fmt.Fprintf(out, "w.signed(int64(%s));\n", expr)
	case reflect.Uint8:
		fmt.Fprintf(out, "w.byte(byte(%s));\n", expr)
	case reflect.Uint16, reflect.Uint32, reflect.Uint64:
		fmt.Fprintf(out, "w.unsigned(uint64(%s));\n", expr)
	case reflect.Float32, reflect.Float64:
		fmt.Fprintf(out, "w.float64(float64(%s));\n", expr)
	case reflect.String:
		fmt.Fprintf(out, "w.string(string(%s));\n", expr)
	case reflect.Pointer:
		fmt.Fprintf(out, "w.boolean(%s != nil); if %s != nil {\n", expr, expr)
		fmt.Fprintf(out, "if !w.allocate(1, authorityBinarySizeOf[%s]()) { return };\n", g.typeName(typ.Elem()))
		g.write(out, typ.Elem(), "(*"+expr+")")
		fmt.Fprintln(out, "}")
	case reflect.Array, reflect.Slice:
		if typ.Kind() == reflect.Slice {
			fmt.Fprintf(out, "if !w.collection(len(%s), %s == nil, authorityBinarySizeOf[%s]()) { return };\n", expr, expr, g.typeName(typ.Elem()))
		}
		if typ.Elem().Kind() == reflect.Uint8 {
			fmt.Fprintf(out, "w.raw(%s[:]);\n", expr)
		} else {
			i := g.local()
			fmt.Fprintf(out, "for %s := range %s { if w.err != nil { return };\n", i, expr)
			g.write(out, typ.Elem(), expr+"["+i+"]")
			fmt.Fprintln(out, "}")
		}
	case reflect.Map:
		keys, key, value := g.local(), g.local(), g.local()
		fmt.Fprintf(out, "if !w.collection(len(%s), %s == nil, 2*(authorityBinarySizeOf[%s]()+authorityBinarySizeOf[%s]()+16)) { return };\n", expr, expr, g.typeName(typ.Key()), g.typeName(typ.Elem()))
		fmt.Fprintf(out, "%s := make([]%s, 0, len(%s)); for %s := range %s { %s = append(%s, %s) }; slices.Sort(%s);\n", keys, g.typeName(typ.Key()), expr, key, expr, keys, keys, key, keys)
		fmt.Fprintf(out, "for _, %s := range %s { if w.err != nil { return }; %s := %s[%s];\n", key, keys, value, expr, key)
		g.write(out, typ.Key(), key)
		g.write(out, typ.Elem(), value)
		fmt.Fprintln(out, "}")
	default:
		panic(typ)
	}
}

func (g *authorityBinaryGenerator) read(out *bytes.Buffer, typ reflect.Type, expr string) {
	cast := g.typeName(typ)
	switch typ.Kind() {
	case reflect.Struct:
		fmt.Fprintf(out, "r.read%s(&%s);\n", g.name(typ), expr)
	case reflect.Bool:
		fmt.Fprintf(out, "%s = %s(r.boolean());\n", expr, cast)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		bits := fmt.Sprint(typ.Bits())
		if typ.Kind() == reflect.Int {
			bits = "strconv.IntSize"
		}
		fmt.Fprintf(out, "%s = %s(r.signed(%s));\n", expr, cast, bits)
	case reflect.Uint8:
		fmt.Fprintf(out, "%s = %s(r.byte());\n", expr, cast)
	case reflect.Uint16, reflect.Uint32, reflect.Uint64:
		fmt.Fprintf(out, "%s = %s(r.unsigned(%d));\n", expr, cast, typ.Bits())
	case reflect.Float32, reflect.Float64:
		fmt.Fprintf(out, "%s = %s(r.float64());\n", expr, cast)
	case reflect.String:
		fmt.Fprintf(out, "%s = %s(r.string());\n", expr, cast)
	case reflect.Pointer:
		fmt.Fprintf(out, "if r.boolean() { if !r.allocate(1, authorityBinarySizeOf[%s]()) { return }; %s = new(%s);\n", g.typeName(typ.Elem()), expr, g.typeName(typ.Elem()))
		g.read(out, typ.Elem(), "(*"+expr+")")
		fmt.Fprintln(out, "}")
	case reflect.Array:
		if typ.Elem().Kind() == reflect.Uint8 {
			fmt.Fprintf(out, "copy(%s[:], r.raw(%d));\n", expr, typ.Len())
		} else {
			i := g.local()
			fmt.Fprintf(out, "for %s := range %s { if r.err != nil { return };\n", i, expr)
			g.read(out, typ.Elem(), expr+"["+i+"]")
			fmt.Fprintln(out, "}")
		}
	case reflect.Slice:
		n, present, i := g.local(), g.local(), g.local()
		fmt.Fprintf(out, "%s, %s := r.collection(%d, authorityBinarySizeOf[%s]()); if r.err != nil { return }; if %s { %s = make(%s, %s);\n", n, present, authorityBinaryMinimumBytes(typ.Elem()), g.typeName(typ.Elem()), present, expr, cast, n)
		if typ.Elem().Kind() == reflect.Uint8 {
			fmt.Fprintf(out, "copy(%s, r.raw(%s));\n", expr, n)
		} else {
			fmt.Fprintf(out, "for %s := range %s { if r.err != nil { return };\n", i, expr)
			g.read(out, typ.Elem(), expr+"["+i+"]")
			fmt.Fprintln(out, "}")
		}
		fmt.Fprintln(out, "}")
	case reflect.Map:
		n, present, key, value, prior, i := g.local(), g.local(), g.local(), g.local(), g.local(), g.local()
		fmt.Fprintf(out, "%s, %s := r.collection(%d, 2*(authorityBinarySizeOf[%s]()+authorityBinarySizeOf[%s]()+16)); if r.err != nil { return }; if %s { %s = make(%s, %s); var %s %s;\n", n, present, authorityBinaryMinimumBytes(typ.Key())+authorityBinaryMinimumBytes(typ.Elem()), g.typeName(typ.Key()), g.typeName(typ.Elem()), present, expr, cast, n, prior, g.typeName(typ.Key()))
		fmt.Fprintf(out, "for %s := 0; %s < %s; %s++ { if r.err != nil { return }; var %s %s; var %s %s;\n", i, i, n, i, key, g.typeName(typ.Key()), value, g.typeName(typ.Elem()))
		g.read(out, typ.Key(), key)
		fmt.Fprintf(out, "if %s > 0 && %s <= %s { r.fail(\"unordered or duplicate map key\"); return }; %s = %s;\n", i, key, prior, prior, key)
		g.read(out, typ.Elem(), value)
		fmt.Fprintf(out, "%s[%s] = %s; } }\n", expr, key, value)
	default:
		panic(typ)
	}
}

func authorityBinaryMinimumBytes(typ reflect.Type) int {
	switch typ.Kind() {
	case reflect.Struct:
		n := 0
		for i := 0; i < typ.NumField(); i++ {
			n += authorityBinaryMinimumBytes(typ.Field(i).Type)
		}
		return n
	case reflect.Array:
		return typ.Len() * authorityBinaryMinimumBytes(typ.Elem())
	case reflect.Float32, reflect.Float64:
		return 8
	default:
		return 1
	}
}
