package roomhost

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"time"

	"gddoom/internal/lobby"
	"gddoom/internal/mapdata"
	"gddoom/internal/wad"
)

type storedPack struct {
	Pack  lobby.Pack `json:"pack"`
	Sizes []int64    `json:"sizes"`
}

func (m *Manager) initUploads() error {
	if m.config.UploadDir == "" {
		return nil
	}
	if m.config.UploadQuota == 0 {
		m.config.UploadQuota = 512 << 20
	}
	if m.config.UploadQuota < 1 {
		return errors.New("upload quota must be positive")
	}
	directory, err := filepath.Abs(m.config.UploadDir)
	if err != nil {
		return err
	}
	m.config.UploadDir = directory
	if err := os.MkdirAll(directory, 0700); err != nil {
		return err
	}
	lock, err := os.OpenFile(filepath.Join(directory, ".lock"), os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return err
	}
	if err := tryLockUploadFile(lock); err != nil {
		lock.Close()
		return fmt.Errorf("upload storage is already in use or cannot be locked: %w", err)
	}
	m.uploadLock = lock
	entries, err := os.ReadDir(directory)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.Name() == ".lock" {
			continue
		}
		if strings.HasPrefix(entry.Name(), ".upload-") {
			if err := os.RemoveAll(filepath.Join(directory, entry.Name())); err != nil {
				return err
			}
			continue
		}
		if !entry.IsDir() || !validPackDirectory(entry.Name()) {
			return fmt.Errorf("unexpected file in upload storage: %q", entry.Name())
		}
		data, err := os.ReadFile(filepath.Join(directory, entry.Name(), "pack.json"))
		if err != nil || len(data) > 256<<10 {
			return fmt.Errorf("invalid uploaded pack record %q", entry.Name())
		}
		var stored storedPack
		if err := json.Unmarshal(data, &stored); err != nil {
			return err
		}
		if err := lobby.ValidatePack(stored.Pack); err != nil || stored.Pack.ID != entry.Name() || len(stored.Sizes) != len(stored.Pack.WADHashes) || len(stored.Sizes) > lobby.MaxUploadFiles {
			return fmt.Errorf("invalid uploaded pack identity %q", entry.Name())
		}
		var paths []string
		var total int64
		for i, size := range stored.Sizes {
			if size < 12 || size > lobby.MaxUploadFileBytes {
				return errors.New("invalid uploaded WAD size")
			}
			path := filepath.Join(directory, entry.Name(), strconv.Itoa(i)+".wad")
			info, err := os.Lstat(path)
			if err != nil || !info.Mode().IsRegular() || info.Size() != size {
				return fmt.Errorf("uploaded WAD changed: %s", path)
			}
			paths = append(paths, path)
			total += size
		}
		if total > lobby.MaxUploadBytes || total > m.config.UploadQuota-m.uploadBytes {
			return errors.New("uploaded content exceeds configured disk quota")
		}
		pack, err := inspectUploadPaths(stored.Pack.ID, stored.Pack.Name, paths)
		if err != nil || !slices.Equal(pack.Pack.WADHashes, stored.Pack.WADHashes) || !slices.Equal(pack.Pack.Maps, stored.Pack.Maps) {
			return fmt.Errorf("uploaded pack validation failed: %q: %v", entry.Name(), err)
		}
		// Names survive restarts; permissions are regenerated by initContent.
		pack.Pack.Files = slices.Clone(stored.Pack.Files)
		if _, exists := m.packs[pack.Pack.ID]; exists || len(m.packs) >= lobby.MaxPacks {
			return errors.New("uploaded pack conflicts with or exceeds configured catalog")
		}
		m.packs[pack.Pack.ID] = pack
		m.config.Packs = append(m.config.Packs, pack)
		m.uploadBytes += total
	}
	return nil
}

func validPackDirectory(name string) bool {
	data, err := hex.DecodeString(name)
	return err == nil && len(data) == 32 && name == strings.ToLower(name)
}

func (m *Manager) uploadHTTP(w http.ResponseWriter, r *http.Request) {
	m.mu.Lock()
	if m.config.UploadDir == "" {
		m.mu.Unlock()
		writeError(w, reject(http.StatusNotFound, "WAD uploads are disabled"))
		return
	}
	if m.closed || m.ctx.Err() != nil {
		m.mu.Unlock()
		writeError(w, reject(http.StatusServiceUnavailable, "lobby is stopping"))
		return
	}
	m.pruneLocked(time.Now())
	if !m.allowCreateLocked(m.remoteAddress(r), time.Now()) {
		m.mu.Unlock()
		writeError(w, reject(http.StatusTooManyRequests, "please wait before uploading more content"))
		return
	}
	select {
	case m.uploadSlot <- struct{}{}:
	default:
		m.mu.Unlock()
		writeError(w, reject(http.StatusServiceUnavailable, "another WAD upload is in progress"))
		return
	}
	m.wg.Add(1)
	m.mu.Unlock()
	defer m.wg.Done()
	defer func() { <-m.uploadSlot }()
	// Shutdown and the upload deadline close slow bodies, releasing the worker
	// slot even when the sender stalls between multipart chunks.
	ctx, cancel := context.WithTimeout(r.Context(), 2*time.Minute)
	defer cancel()
	stopManager := context.AfterFunc(m.ctx, cancel)
	defer stopManager()
	r.Body = http.MaxBytesReader(w, r.Body, lobby.MaxUploadBytes+(1<<20))
	body := r.Body
	controller := http.NewResponseController(w)
	deadline, _ := ctx.Deadline()
	_ = controller.SetReadDeadline(deadline)
	defer controller.SetReadDeadline(time.Time{})
	stopBody := context.AfterFunc(ctx, func() {
		// Interrupt a pending socket Read before Close can wait for its mutex.
		_ = controller.SetReadDeadline(time.Now())
		_ = body.Close()
	})
	defer stopBody()
	pack, err := m.receiveUpload(ctx, r)
	if err != nil {
		writeError(w, err)
		return
	}
	writeJSON(w, http.StatusCreated, pack)
}

func (m *Manager) receiveUpload(ctx context.Context, r *http.Request) (lobby.Pack, error) {
	reader, err := r.MultipartReader()
	if err != nil {
		return lobby.Pack{}, reject(http.StatusBadRequest, "upload requires multipart form data")
	}
	part, err := reader.NextPart()
	if err != nil || part.FormName() != "metadata" {
		return lobby.Pack{}, reject(http.StatusBadRequest, "upload metadata must be the first part")
	}
	metadataBytes, err := io.ReadAll(io.LimitReader(part, lobby.MaxRequestBytes+1))
	if err != nil || len(metadataBytes) > lobby.MaxRequestBytes {
		return lobby.Pack{}, reject(http.StatusBadRequest, "upload metadata is too large")
	}
	var metadata lobby.UploadMetadata
	decoder := json.NewDecoder(strings.NewReader(string(metadataBytes)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&metadata); err != nil {
		return lobby.Pack{}, reject(http.StatusBadRequest, "invalid upload metadata")
	}
	if err := decoder.Decode(new(any)); err != io.EOF {
		return lobby.Pack{}, reject(http.StatusBadRequest, "upload requires one metadata object")
	}
	if err := lobby.ValidateUploadMetadata(metadata); err != nil {
		return lobby.Pack{}, reject(http.StatusBadRequest, err.Error())
	}
	hashes := make([]string, 0, len(metadata.Files))
	var total int64
	for _, file := range metadata.Files {
		hashes = append(hashes, file.SHA256)
		total += file.Size
	}
	identity := sha256.Sum256([]byte(strings.Join(hashes, "\n")))
	id := hex.EncodeToString(identity[:])
	m.mu.Lock()
	var duplicate *lobby.Pack
	for _, pack := range m.packs {
		if slices.Equal(pack.Pack.WADHashes, hashes) {
			p := clonePack(pack.Pack)
			duplicate = &p
			break
		}
	}
	full := len(m.packs) >= lobby.MaxPacks
	m.mu.Unlock()
	if duplicate == nil && (full || total > m.config.UploadQuota-m.uploadBytes) {
		return lobby.Pack{}, reject(http.StatusInsufficientStorage, "uploaded content catalog or disk quota is full")
	}
	directory := ""
	if duplicate == nil {
		directory, err = os.MkdirTemp(m.config.UploadDir, ".upload-")
		if err != nil {
			return lobby.Pack{}, err
		}
		defer os.RemoveAll(directory)
	}
	var paths []string
	for i, file := range metadata.Files {
		if err := ctx.Err(); err != nil {
			return lobby.Pack{}, err
		}
		part, err := reader.NextPart()
		if err != nil || part.FormName() != "file"+strconv.Itoa(i) {
			return lobby.Pack{}, reject(http.StatusBadRequest, "WAD parts must match the declared stack order")
		}
		var target io.Writer = io.Discard
		var output *os.File
		if duplicate == nil {
			path := filepath.Join(directory, strconv.Itoa(i)+".wad")
			output, err = os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
			if err != nil {
				return lobby.Pack{}, err
			}
			target = output
			paths = append(paths, path)
		}
		digest := sha256.New()
		n, copyErr := io.Copy(io.MultiWriter(target, digest), io.LimitReader(part, file.Size+1))
		if output != nil {
			err = output.Close()
		}
		if copyErr != nil || err != nil || n != file.Size || hex.EncodeToString(digest.Sum(nil)) != file.SHA256 {
			return lobby.Pack{}, reject(http.StatusBadRequest, "uploaded WAD size or SHA-256 does not match metadata")
		}
	}
	if _, err := reader.NextPart(); err != io.EOF {
		return lobby.Pack{}, reject(http.StatusBadRequest, "unexpected extra upload part")
	}
	if duplicate != nil {
		return *duplicate, nil
	}
	pack, err := inspectUploadPaths(id, metadata.Name, paths)
	if err != nil {
		return lobby.Pack{}, reject(http.StatusBadRequest, "invalid WAD stack: "+err.Error())
	}
	pack.Pack.Files = make([]lobby.PackFile, len(metadata.Files))
	for i, file := range metadata.Files {
		pack.Pack.Files[i].Name = file.Name
	}
	pack, err = m.prepareContent(pack)
	if err != nil {
		return lobby.Pack{}, err
	}
	if err := ctx.Err(); err != nil {
		return lobby.Pack{}, err
	}
	sizes := make([]int64, len(metadata.Files))
	for i, file := range metadata.Files {
		sizes[i] = file.Size
	}
	data, err := json.Marshal(storedPack{Pack: pack.Pack, Sizes: sizes})
	if err != nil {
		return lobby.Pack{}, err
	}
	if err := os.WriteFile(filepath.Join(directory, "pack.json"), data, 0400); err != nil {
		return lobby.Pack{}, err
	}
	for _, path := range paths {
		if err := os.Chmod(path, 0400); err != nil {
			return lobby.Pack{}, err
		}
	}
	destination := filepath.Join(m.config.UploadDir, id)
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.closed || ctx.Err() != nil {
		return lobby.Pack{}, reject(http.StatusServiceUnavailable, "lobby is stopping")
	}
	if _, exists := m.packs[id]; exists {
		return lobby.Pack{}, reject(http.StatusConflict, "content identity conflicts with an installed pack")
	}
	if err := os.Rename(directory, destination); err != nil {
		return lobby.Pack{}, err
	}
	for i := range pack.Paths {
		if !pack.Pack.Files[i].Downloadable {
			pack.Paths[i] = filepath.Join(destination, strconv.Itoa(i)+".wad")
		}
	}
	m.packs[id] = pack
	m.config.Packs = append(m.config.Packs, pack)
	m.uploadBytes += total
	return clonePack(pack.Pack), nil
}

func inspectUploadPaths(id, name string, paths []string) (ContentPack, error) {
	pack := ContentPack{Pack: lobby.Pack{ID: id, Name: name}, Paths: slices.Clone(paths)}
	var files []*wad.File
	var totalLumps uint64
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			return ContentPack{}, err
		}
		if len(data) < 12 {
			return ContentPack{}, errors.New("WAD header is truncated")
		}
		lumps := uint64(binary.LittleEndian.Uint32(data[4:8]))
		totalLumps += lumps
		if lumps > 100000 || totalLumps > 200000 {
			return ContentPack{}, errors.New("WAD directory contains too many lumps")
		}
		file, err := wad.OpenData(path, data)
		if err != nil {
			return ContentPack{}, errors.New("WAD directory is invalid")
		}
		digest := sha256.Sum256(data)
		pack.Pack.WADHashes = append(pack.Pack.WADHashes, hex.EncodeToString(digest[:]))
		files = append(files, file)
	}
	merged := wad.Merge(files...)
	if err := validateUploadGeometry(merged); err != nil {
		return ContentPack{}, err
	}
	names, err := uniqueMapNames(merged)
	if err != nil {
		return ContentPack{}, err
	}
	for _, name := range names {
		if _, err := mapdata.LoadMap(merged, name); err == nil {
			pack.Pack.Maps = append(pack.Pack.Maps, string(name))
		}
	}
	if err := lobby.ValidatePack(pack.Pack); err != nil {
		return ContentPack{}, errors.New("WAD stack has no usable maps or invalid metadata")
	}
	return pack, nil
}
